---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP Dokumentation zur Automatisierung
    url: "/index.html"
  - title: Was ist neu
    url: "/whats_new.html"
  - section: get-started
  - section: rest
  - section: workflows
  - section: sw-tools
  - section: migrate
  - section: reference
  - section: additional
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Versionshinweise
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - title: ONTAP Automatisierungsoptionen
      url: "/get-started/ontap_automation_options.html"
    - title: Ihr erster API-Aufruf
      url: "/get-started/first_call.html"
  - title: ONTAP REST API
    links:
    - title: Einzelheiten zur REST-Implementierung
      url: "/rest/rest_web_services_foundation.html"
    - title: RBAC-Sicherheit
      url: "/rest/rbac_overview.html"
    - title: Zusammenfassung der REST-Ressourcen
      url: "/resources/overview_categories.html"
    - title: API-Referenz
      url: "/reference/api_reference.html"
  - title: Automatisierung
    links:
    - title: Workflows
      url: "/workflows/prepare_workflows.html"
    - title: Python-Client-Bibliothek
      url: "/python/overview_pcl.html"
  - title: Migration zur REST-API
    links:
    - title: ONTAPI Deaktivierung
      url: "/migrate/overview.html"
    - title: ONTAPI für REST-Zuordnung
      url: "/migrate/mapping.html"
    - title: Performance-Zähler
      url: "/migrate/performance-counters.html"
    - title: Blog-Artikel
      url: "/migrate/blogs.html"
  - title: Wissen und Support
    links:
    - title: Weitere Ressourcen
      url: "/additional/resources.html"
    - title: ONTAP 9 Dokumentation
      url: https://docs.netapp.com/us-en/ontap/
    - title: ONTAP Select Dokumentation
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
