---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP Dokumentation zur Automatisierung
    url: "/index.html"
  - title: Was ist neu
    entries:
    - title: Neuerungen bei der ONTAP REST API
      url: "/whats-new.html"
    - title: Änderungen an ONTAP-REST-API-Aufrufen
      url: "/api-changes.html"
  - section: get-started
  - section: rest
  - section: workflows
  - section: sw-tools
  - section: migrate
  - section: reference
  - section: additional
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
