---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP Dokumentation zur Automatisierung
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: reference
  - section: automate
  - section: migrate
  - section: additional
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Versionshinweise
      url: "/rn/whats_new.html"
    - title: ONTAP Automatisierungsoptionen
      url: "/get-started/ontap_automation_options.html"
    - title: Die Verwendung der REST-API wird vorbereitet
      url: "/get-started/prepare_rest.html"
    - title: Ihr erster API-Aufruf
      url: "/get-started/first_call.html"
  - title: ONTAP REST API
    links:
    - title: Einzelheiten zur REST-Implementierung
      url: "/rest/rest_web_services_foundation.html"
    - title: Weitere Überlegungen
      url: "/rest/object_references_and_access.html"
    - title: Zusammenfassung der REST-Ressourcen
      url: "/resources/overview_categories.html"
    - title: API-Referenz
      url: "/reference/api_reference.html"
  - title: Automatisierung
    links:
    - title: Python-Client-Bibliothek
      url: "/python/overview_pcl.html"
    - title: ONTAP und Ansible
      url: "/automate/ontap_ansible.html"
    - title: Blogs zur Automatisierung
      url: "/automate/blogs.html"
  - title: Migration zur REST-API
    links:
    - title: ONTAPI Deaktivierung
      url: "/migrate/overview.html"
    - title: ONTAPI für REST-Zuordnung
      url: "/migrate/mapping.html"
    - title: Performance-Zähler
      url: "/migrate/performance-counters.html"
    - title: Blog-Artikel
      url: "/migrate/blogs.html"
  - title: Mehr Ressourcen
    links:
    - title: Weitere Informationen
      url: "/additional/get_more_information.html"
    - title: NetApp DevNet
      url: https://devnet.netapp.com/restapi.php
    - title: ONTAP 9 Dokumentation
      url: https://docs.netapp.com/us-en/ontap/
    - title: ONTAP Select Dokumentation
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: Gesamte ONTAP Produktdokumentation
