---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new features, new in release 
summary: NetApp aktualisiert regelmäßig das ONTAP REST API, um Ihnen neue Funktionen, Verbesserungen und Fehlerbehebungen zu bieten. 
---
= Was ist neu mit der ONTAP REST API und Automatisierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp aktualisiert regelmäßig das ONTAP REST API, um Ihnen neue Funktionen, Verbesserungen und Fehlerbehebungen zu bieten.


TIP: Lesen Sie auch die https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP"^] Für weitere Informationen, einschließlich bekannter Einschränkungen oder Probleme.



== ONTAP 9.15.1

ONTAP 9.15.1 erweitert weiterhin die Funktionen der ONTAP-REST-API. Das Update für diese Version ist relativ bescheiden, da drei neue Endpunkte eine neue Funktion unterstützen.

NFS über TLS:: Mit dieser Funktion stehen drei neue Endpunkte zur Verfügung. Sie können diese API-Aufrufe ausgeben, um alle NFS-over-TLS-Schnittstellen abzurufen, eine bestimmte Schnittstelle anhand der UUID abzurufen und die Konfigurationseigenschaften für eine TLS-Schnittstelle zu aktualisieren. Insgesamt bieten diese API-Aufrufe eine Entsprechung zum Satz von `vserver nfs tls interface` CLI-Befehle.



CAUTION: NFS über TLS ist in ONTAP 9.15.1 als öffentliche Vorschau verfügbar. Diese Funktion wird als Vorschauangebot für Produktions-Workloads mit ONTAP 9.15.1 nicht unterstützt.



== ONTAP 9.14.1

Die Version ONTAP 9.14.1 enthält mehr als drei Dutzend neue API-Aufrufe, die die Funktionen der ONTAP-REST-API weiter erweitern. Diese Endpunkte unterstützen mehrere neue ONTAP-Funktionen sowie Updates vorhandener Funktionen. Dieser Release konzentriert sich in erster Linie auf Sicherheitsverbesserungen, umfasst aber auch Verbesserungen bei NAS-, QOS- und Performance-Kennzahlen.

Sicherheit:: Es gibt zwei wichtige Sicherheitsfunktionen, die mit ONTAP 9.14.1 eingeführt wurden. Open Authorization (OAuth 2.0) ist ein Token-basiertes Framework, mit dem der Zugriff auf Ihre ONTAP Storage-Ressourcen eingeschränkt werden kann. Sie können sie zusammen mit Clients verwenden, die über die REST-API auf ONTAP zugreifen. Die Konfiguration kann mit jeder der ONTAP-Administrationsschnittstellen, einschließlich der REST-API, durchgeführt werden. Die Version ONTAP 9.14.1 enthält zudem Unterstützung für Cisco Duo, das für die zwei-Faktor-Authentifizierung bei SSH-Anmeldungen sorgt. Sie können Duo für den Betrieb auf ONTAP-Cluster- oder SVM-Ebene konfigurieren. Zusätzlich zu diesen beiden neuen Funktionen wurden mehrere Endpunkte hinzugefügt, um die Kontrolle über Ihre Schlüsselspeicher zu verbessern.
FPolicy-persistenter Storage:: FPolicy stellt eine Plattform für das ONTAP-Richtlinienmanagement bereit. Es stellt einen Container für die verschiedenen Komponenten oder Elemente, wie z. B. Ereignisse und die Richtlinien-Engine, bereit. Sie können jetzt mit der REST-API einen persistenten Speicher für die ONTAP FPolicy Konfiguration und Ereignisse konfigurieren und verwalten. Jede SVM kann über einen persistenten Speicher verfügen, der für mehrere Richtlinien in der SVM freigegeben wird.
QOS-Optionen:: Es wurden zwei Endpunkte eingeführt, mit denen Sie QOS-Optionen für das Cluster abrufen und festlegen können. Sie können beispielsweise einen Prozentsatz der verfügbaren Systemverarbeitungsressourcen für Hintergrundaufgaben reservieren.
Performance-Metriken:: ONTAP speichert statistische Informationen über die Betriebseigenschaften des Systems. Diese Informationen werden in einem Datenbankformat dargestellt, das aus Tabellen und Zeilen besteht. Mit ONTAP 9.14.1 werden zusätzliche metrische Daten in verschiedenen Ressourcenkategorien hinzugefügt, darunter Fibre Channel, iSCSI, LUNs und NVME. Durch diese zusätzlichen Kennzahlen rückt die ONTAP-REST-API weiterhin näher an die Parität mit der Data ONTAP-API (ONTAPI oder ZAPI) heran.
Verschiedene Verbesserungen:: Es gibt mehrere weitere Verbesserungen, die in Abhängigkeit von Ihrer Umgebung hilfreich sein können. Diese neuen Endpunkte verbessern den Zugriff auf die SAN-Initiatoren, die Steuerung der Host-Cache-Einstellungen sowie den Zugriff auf einzelne AutoSupport-Nachrichten.




== ONTAP 9.13.1

Mit mehr als zwei Dutzend neuer API-Aufrufe erweitert ONTAP 9.13.1 weiterhin die Funktionen der ONTAP-REST-API. Diese Endpunkte unterstützen neue ONTAP-Funktionen sowie Verbesserungen vorhandener Funktionen. Dieser Release konzentriert sich auf Verbesserungen bei Sicherheit, Ressourcenmanagement, erweiterte SVM-Konfigurationsoptionen und Performance-Kennzahlen.

Ressourcen-Tagging:: Sie können Tags verwenden, um REST-API-Ressourcen zu gruppieren. Auf diese Weise können Sie verwandte Ressourcen innerhalb eines bestimmten Projekts oder einer bestimmten Organisationsgruppe zuordnen. Mithilfe von Tags können Sie Ressourcen effektiver organisieren und verfolgen.
Konsistenzgruppen:: ONTAP 9.13.1 erweitert weiterhin die Verfügbarkeit von Leistungszählerdaten. Sie können nun auf diese Art von statistischen Informationen zugreifen, um die historische Leistung und Kapazität von Consistency Groups zu verfolgen. Darüber hinaus wurden Verbesserungen integriert, die es ermöglichen, die Beziehungen zwischen übergeordneten und untergeordneten Gruppen zwischen Konsistenzgruppen zu konfigurieren und zu verwalten.
DNS-Konfiguration pro SVM:: Die vorhandenen DNS-Endpunkte wurden erweitert, um die Ausführung einer DNS-Domänen- und Serverkonfiguration für einzelne SVMs zu ermöglichen.
EMS-Rollenkonfiguration:: Die bestehende EMS-Support-Funktion wurde erweitert, um die Verwaltung von Rollen und die den Rollen zugewiesene Zugangskontrollkonfiguration zu ermöglichen. Dies bietet die Möglichkeit, die Ereignisse und Meldungen basierend auf der Rollenkonfiguration zu begrenzen oder zu filtern.
Sicherheit:: Sie können die REST-API verwenden, um die zeitbasierten TOTP-Profile (One-Time Password) für Konten zu konfigurieren, die sich über SSH anmelden und auf ONTAP zugreifen. Darüber hinaus wurden die Schlüsselmanager-Endpunkte erweitert, um eine Wiederherstellung von einem bestimmten Schlüsselmanagementserver aus zu ermöglichen.
CIFS-Konfiguration pro SVM:: Die vorhandenen CIFS-Endpunkte wurden erweitert, um eine Aktualisierung der Konfiguration einer spezifischen SVM zu ermöglichen.
S3-Bucket-Regeln:: Die bestehenden S3-Bucket-Endpunkte wurden erweitert und um eine Regeldefinition erweitert. Jede Regel ist ein Listenobjekt und definiert die Aktionen, die für ein Objekt innerhalb des Buckets ausgeführt werden sollen. Gemeinsam ermöglichen diese Regeln ein besseres Management des Lebenszyklus von S3 Buckets.




== ONTAP 9.12.1

ONTAP 9.12.1 erweitert mit über vierzig neuen API-Aufrufen kontinuierlich die Funktionen der ONTAP REST-API. Diese Endpunkte unterstützen neue ONTAP-Funktionen sowie Verbesserungen vorhandener Funktionen. In dieser Version stehen Verbesserungen bei den Sicherheits- und NAS-Funktionen im Mittelpunkt.

Verbesserte Sicherheit:: Amazon Web Services umfasst einen Verschlüsselungsmanagement-Service, der sicheren Storage für Schlüssel und andere Geheimnisse bietet. Sie können über die REST-API auf diesen Service zugreifen, sodass ONTAP seine Schlüssel sicher in der Cloud speichern kann. Darüber hinaus können Sie die mit NetApp Storage Encryption verwendeten Authentifizierungsschlüssel erstellen und auflisten.
Active Directory:: Sie können die für ein ONTAP-Cluster definierten Active Directory-Konten verwalten. Dies umfasst das Erstellen neuer Konten sowie das Anzeigen, Aktualisieren und Löschen von Konten.
CIFS-Gruppenrichtlinien:: DIE REST-API wurde erweitert, um die Erstellung und das Management von CIFS-Gruppenrichtlinien zu unterstützen. Die Konfigurationsinformationen sind verfügbar und über Gruppenrichtlinienobjekte verwaltet, die auf alle oder bestimmte SVMs angewendet werden.




== ONTAP 9.11.1

ONTAP 9.11.1 erweitert weiterhin die Funktionen der ONTAP REST API mit nahezu hundert neuen API-Aufrufen. Diese Endpunkte unterstützen die neuen ONTAP-Funktionen sowie Verbesserungen vorhandener Funktionen. Dieses Release konzentriert Data ONTAP sich darauf, die Migration von Kunden auf die ONTAP REST API (ONTAPI oder ZAPI) zu unterstützen.

Granulare RBAC:: Die rollenbasierte Zugriffssteuerung (Role Based Access Control, RBAC) von ONTAP wurde verbessert und bietet nun zusätzliche Granularität. Über die REST-API können Sie je nach Bedarf die herkömmlichen Rollen verwenden oder neue benutzerdefinierte Rollen erstellen. Jede Rolle ist mit einem oder mehreren Berechtigungen verknüpft. Jede Rolle identifiziert einen REST-API-Aufruf oder einen CLI-Befehl zusammen mit der Zugriffsebene. Neue Zugriffsebenen sind für REST-Rollen wie z. B. verfügbar `read_create` Und `read_modify`. Diese Verbesserung bietet Parität mit der Data ONTAP API (ONTAPI oder ZAPI) und unterstützt die Datenmigration in DIE REST API. Siehe link:rest/rbac_overview.html["RBAC-Sicherheit"] Finden Sie weitere Informationen.
Performance-Zähler:: Frühere ONTAP-Releases haben statistische Informationen über die betrieblichen Eigenschaften des Systems erhalten. In der Version 9.11.1 wurden diese Informationen verbessert und sind nun über DIE REST API verfügbar. Ein Administrator oder automatisierter Prozess kann auf die Daten zugreifen, um die Systemleistung zu ermitteln. Die vom Zählermanager-Subsystem aufgesetzten statistischen Informationen werden anhand von Tabellen und Zeilen in einem Datenbankformat dargestellt. Diese Verbesserung bringt das ONTAP REST API näher an Parität mit dem Data ONTAP API (ONTAPI oder ZAPI).
Aggregatmanagement:: Das Management von ONTAP-Storage-Aggregaten wurde verbessert. Mithilfe der aktualisierten REST-Endpunkte können Aggregate online und offline verschoben oder die Reserveteile gemanagt werden.
IP-Subnetz-Funktion:: Die ONTAP-Netzwerkfunktion wurde erweitert und unterstützt nun IP-Subnetze. Die REST-API bietet Zugriff auf die Konfiguration und das Management der IP-Subnetze innerhalb eines ONTAP-Clusters.
Verifizierung mehrerer Administratoren:: Die Überprüfungsfunktion für mehrere Administratoren stellt ein flexibles Autorisierungs-Framework zum Schutz des Zugriffs auf ONTAP-Befehle oder -Vorgänge bereit. Sie können Regeln definieren, die die eingeschränkten Befehle identifizieren. Wenn ein Benutzer Zugriff auf einen bestimmten Befehl anfordert, kann die Genehmigung gegebenenfalls von mehreren ONTAP Administratoren erteilt werden.
SnapMirror Verbesserungen:: Die SnapMirror Funktion wurde in verschiedenen Bereichen verbessert, darunter auch die Zeitplanung. Die SnapVault-Beziehungsparität wurde in einer DP-Beziehung zu ONTAP 9.11.1 hinzugefügt auch, die Drosselfunktion, die mit DEM REST API verfügbar ist, hat Parität mit dem Data ONTAP API (ONTAPI oder ZAPI) erreicht. In diesem Zusammenhang wird das Erstellen und Verwalten von Snapshot-Kopien für große Mengen unterstützt.
Storage-Pools:: Es wurden mehrere Endpunkte hinzugefügt, um den Zugriff auf die ONTAP Storage-Pools zu ermöglichen. Das Erstellen und Auflisten der Speicherpools in einem Cluster sowie das Aktualisieren und Löschen bestimmter Pools nach ID werden unterstützt.
Name Services Cache Support:: ONTAP Name Services wurden erweitert und unterstützen Cache-Speicherung, wodurch Performance und Ausfallsicherheit verbessert werden. Die Konfiguration des Cache für Namensservices kann nun über DIE REST-API aufgerufen werden. Die Einstellungen können auf mehreren Ebenen angewendet werden, darunter Hosts, unix-Benutzer, unix-Gruppen und Netgroups.
ONTAPI Reporting Tool:: Das ONTAPI Reporting Tool unterstützt Kunden und Partner bei der Identifizierung der ONTAPI-Nutzung in ihrer Umgebung. Neben der Python Software bietet das NetApp Lab on Demand außerdem ein Video und einen weiterentwickelten Support. Dieses Tool bietet eine weitere Ressource bei der Migration von ONTAPI zu ONTAP REST API.




== ONTAP 9.10.1

ONTAP 9.10.1 erweitert weiterhin die Funktionen der ONTAP REST API. Mehr als hundert neue Endpunkte unterstützen neue ONTAP-Funktionen und Verbesserungen vorhandener Funktionen. Im Folgenden finden Sie eine Zusammenfassung der Verbesserungen DER REST API.

Anwendungskonsistenzgruppe:: Eine Konsistenzgruppe ist ein Satz von Volumes, die zusammen gruppiert werden, wenn bestimmte Vorgänge wie beispielsweise ein Snapshot durchgeführt werden. Diese Funktion erweitert dieselbe Crash-Konsistenz und Datenintegrität einschließlich Single-Volume-Vorgängen über einen Satz von Volumes hinweg. Dies ist nützlich für Applikationen mit mehreren Volumes.
SVM-Migration:: Sie können eine SVM von einem Quell-Cluster zu einem Ziel-Cluster migrieren. Die neuen Endpunkte bieten vollständige Kontrolle, einschließlich der Möglichkeit, den Migrationsvorgang anzuhalten, fortzusetzen, den Status abzurufen und einen Migrationsvorgang abzubrechen.
Klonen und Managen von Dateien:: Das Klonen und Managen von Dateien auf Volume-Ebene wurden verbessert. Neue REST-Endpunkte unterstützen das Verschieben, Kopieren und Aufteilen von Dateien.
Verbessertes S3-Auditing:: Das Auditing von S3-Ereignissen ist eine Verbesserung der Sicherheit, die es ermöglicht, bestimmte S3-Ereignisse zu verfolgen und zu protokollieren. Ein S3-Audit-Ereigniswähler kann auf Bucket-Basis pro SVM festgelegt werden.
Verteidigung von Ransomware:: ONTAP erkennt Dateien, die möglicherweise eine Ransomware-Bedrohung enthalten. Sie können eine Liste dieser verdächtigen Dateien abrufen oder von einem Volume entfernen.
Verschiedene Verbesserungen der Sicherheit:: Es gibt verschiedene allgemeine Sicherheitsverbesserungen, durch die vorhandene Protokolle erweitert und neue Funktionen eingeführt werden. IPSEC, Verschlüsselungsmanagement, SSH-Konfiguration und Dateiberechtigungen wurden verbessert.
CIFS-Domänen und lokale Gruppen:: Auf Cluster- und SVM-Ebene wurde Unterstützung für CIFS-Domänen hinzugefügt. Sie können die Domänenkonfiguration abrufen sowie bevorzugte Domänen-Controller erstellen und entfernen.
Erweiterte Volume-Analysen:: Volume-Analysen und Metriken wurden um zusätzliche Endpunkte erweitert, um Top-Dateien, Verzeichnisse und Benutzer zu unterstützen.
Support-Verbesserungen:: Der Support wurde durch mehrere neue Funktionen verbessert. Mit dem automatischen Update können Sie Ihre ONTAP Systeme auf dem neuesten Stand halten, indem Sie die neuesten Software-Updates herunterladen und anwenden. Sie können auch die von einem Node generierten Memory Core Dumps abrufen und verwalten.




== ONTAP 9.9.1

ONTAP 9.9.1 erweitert weiterhin die Funktionen der ONTAP REST API. Es gibt neue API-Endpunkte für vorhandene ONTAP Funktionen, einschließlich SAN-Port-Sets und der Sicherheit des Dateiverzeichnisses von Vserver. Außerdem wurden Endpunkte hinzugefügt, um neue ONTAP 9.9.1-Funktionen und -Verbesserungen zu unterstützen. Und auch die dazugehörige Dokumentation wurde verbessert. Im Folgenden finden Sie eine Zusammenfassung der Verbesserungen.

Zuordnen von ONTAPI zu ONTAP 9 REST API:: Um den ONTAP-Automatisierungscode in DIE REST-API zu überführen, bietet NetApp Dokumentation zur API-Zuordnung. Diese Referenz enthält eine Liste der ONTAPI-Aufrufe und das entsprechende Rest-API-Äquivalent für jede. Das Zuordnungsdokument wurde aktualisiert und umfasst nun auch die neuen ONTAP 9.9.1 API-Endpunkte. Siehe link:migrate/mapping.html["ONTAPI-to-REST-API-Zuordnung"] Finden Sie weitere Informationen.
API-Endpunkte für neue ONTAP 9.9.1 Kernfunktionen:: Unterstützung für neue Funktionen von ONTAP 9.9.1, die nicht über die ONTAPI API verfügbar sind, wurde der REST API hinzugefügt. Dazu gehört auch die Unterstützung für verschachtelte Initiatorgruppen und Google Cloud Key Management Services.
Verbesserte Unterstützung für den Übergang von ONTAPI zu REST:: Mehr der bisherigen ONTAPI-Aufrufe haben jetzt entsprechende REST-API-Entsprechungen. Dies umfasst lokale Unix-Benutzer und -Gruppen, Management von NTFS-Dateisicherheit ohne Client-, SAN-Port-Sets und Volume-Speicherplatzattribute. Diese Änderungen sind auch in der aktualisierten ONTAPI to REST Mapping Dokumentation enthalten.
Verbesserte Online-Dokumentation:: Die Referenzseite für die ONTAP Online-Dokumentation enthält nun Etiketten, die das ONTAP-Release angeben, wenn jeder REST-Endpunkt oder Parameter eingeführt wurde, einschließlich neuer mit ONTAP 9.9.1.




== ONTAP 9.8

ONTAP 9.8 erweitert die Breite und Tiefe der ONTAP REST API. Sie umfasst mehrere neue Funktionen, die Ihre Fähigkeit verbessern, die Implementierung und das Management von ONTAP Storage-Systemen zu automatisieren. Außerdem wurde der Support verbessert, um den Übergang von der älteren ONTAPI zu REST zu unterstützen.

Zuordnen von ONTAPI zu ONTAP 9 REST API:: Um Sie bei der Aktualisierung Ihrer ONTAPI-Automatisierung zu unterstützen, bietet NetApp eine Liste von ONTAPI-Aufrufen, die einen oder mehrere Eingabeparameter benötigen, und eine Zuordnung dieser Aufrufe zu dem entsprechenden ONTAP 9 REST API-Aufruf. Siehe link:migrate/mapping.html["ONTAPI-to-REST-API-Zuordnung"] Finden Sie weitere Informationen.
API-Endpunkte für neue ONTAP 9.8 Kernfunktionen:: Die Unterstützung für die neuen Core-Funktionen von ONTAP 9.8, die nicht über ONTAPI verfügbar sind, wurde der REST API hinzugefügt. Dazu gehören REST-API-Unterstützung für ONTAP S3-Buckets und -Services, SnapMirror Business Continuity und Dateisystemanalysen.
Erweiterte Unterstützung für erhöhte Sicherheit:: Die Sicherheit wurde durch die Unterstützung mehrerer Services und Protokolle verbessert, darunter Azure Key Vault, Google Cloud Key Management Services, IPSec und Certificate Signing Requests.
Erweiterungen zur Verbesserung der Einfachheit:: ONTAP 9.8 ermöglicht effizientere und moderne Workflows mithilfe der REST-API. Oneclick Firmware-Updates stehen jetzt beispielsweise für verschiedene Arten von Firmware zur Verfügung.
Verbesserte Online-Dokumentation:: Auf der Seite ONTAP Online-Dokumentation sind nun Etiketten mit ONTAP-Version enthalten, die jeden REST-Endpunkt oder Parameter eingeführt wurden, einschließlich der neuen Version in 9.8.
Verbesserte Unterstützung für den Übergang von ONTAPI zu REST:: Weitere ältere ONTAPI-Aufrufe haben jetzt entsprechende REST-API-Entsprechungen. Es steht auch eine Dokumentation zur Verfügung, mit der ermittelt werden kann, welcher REST-Endpunkt anstelle eines bestehenden ONTAPI-Aufrufs verwendet werden soll.
Erweiterte Performance-Metriken:: Die Performance-Kennzahlen für DIE REST-API wurden auf mehrere neue Storage- und Netzwerkobjekte erweitert.




== ONTAP 9.7

ONTAP 9.7 erweitert den Funktionsumfang der ONTAP REST API, indem es drei neue Ressourcenkategorien einführt, jede mit mehreren REST-Endpunkten:

* NDMP
* Objektspeicher
* SnapLock


ONTAP 9.7 führt außerdem einen oder mehrere neue REST-Endpunkte in mehrere bestehende Ressourcenkategorien ein:

* Cluster
* NAS
* Netzwerkbetrieb
* NVMe
* San
* Sicherheit
* Storage
* Unterstützung




== ONTAP 9.6

ONTAP 9.6 erweitert die URSPRÜNGLICH in ONTAP 9.4 eingeführte REST-API-Unterstützung enorm. Die ONTAP 9.6 REST API unterstützt die meisten ONTAP Konfigurations- und Administrationsaufgaben.

REST APIs in ONTAP 9.6 enthalten die folgenden und viele mehr:

* Cluster-Einrichtung
* Protokollkonfiguration
* Bereitstellung
* Performance Monitoring
* Datensicherung
* Applikationsspezifisches Datenmanagement

