---
sidebar: sidebar 
permalink: resources/cluster.html 
keywords: cluster resources 
summary: Sie können diese API-Aufrufe verwenden, um ONTAP-Cluster und die zugehörigen Ressourcen zu verwalten. 
---
= Cluster-Ressourcen in der ONTAP-REST-API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können diese API-Aufrufe verwenden, um ONTAP-Cluster und die zugehörigen Ressourcen zu verwalten.

.Kapazitäts-Pools
Mit dem Modell der Kapazitäts-Pools können Sie die Storage-Kapazität für jeden Cluster Node aus einem gemeinsam genutzten Pool lizenzieren. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.Chassis
Das Chassis ist das Hardware-Framework, das ein Cluster unterstützt. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Cluster
Ein ONTAP Cluster enthält mindestens einen Knoten sowie die zugehörigen Konfigurationseinstellungen, die das Storage-System definieren. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Zählertabellen
Verschiedene statistische Informationen über ONTAP werden vom Zählermanager-Subsystem erfasst. Sie können auf diese Informationen zugreifen, um die Systemleistung zu bewerten. Dieser Ressourcentyp wurde mit ONTAP 9.11 eingeführt.

.Firmware
Sie können einen Verlauf der Firmware-Aktualisierungsanforderungen abrufen. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.Jobs
Asynchrone REST-API-Anforderungen werden über eine Hintergrundaufgabe ausgeführt, die durch einen Job verankert ist. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Lizenzinstanz
Jede Lizenz kann als separates Paket gemanagt werden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Lizenzmanager
Sie können Konfiguration und andere Informationen zu jeder Lizenz-Manager-Instanz, die einem ONTAP-Cluster zugeordnet ist, verwalten. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.Lizenzen Zu Haben
Die Lizenzen ermöglichen es Ihnen, spezifische ONTAP Funktionen und Features zu implementieren. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Mediator-Ping
Sie können den BlueXP Cloud-Dienst anpingen. Dieser Ressourcentyp ist neu in ONTAP 9.17.1.

.Mediatoren
Sie können den mit MetroCluster verknüpften Mediator verwalten und die Mediatorinstanz hinzufügen oder entfernen. Dieser Ressourcentyp ist neu in ONTAP 9.8 und wurde mit 9.17.1 aktualisiert.

.MetroCluster
Sie können eine MetroCluster Implementierung erstellen und managen, einschließlich dem Ausführen von Switchover- oder Switchback-Vorgängen. Dieser Ressourcentyp ist neu in ONTAP 9.8 und aktualisiert mit 9.11.

.MetroCluster Diagnose
Sie können einen Diagnosevorgang bei einer MetroCluster-Bereitstellung durchführen und die Ergebnisse abrufen. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.MetroCluster DR-Gruppen
Sie können Vorgänge für die MetroCluster DR-Gruppen durchführen. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.MetroCluster Interconnects
Sie können den MetroCluster-Verbindungsstatus abrufen. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.MetroCluster-Knoten
Sie können den Status der einzelnen Nodes in einer MetroCluster-Bereitstellung abrufen. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.MetroCluster Betrieb
Sie können eine Liste der kürzlich ausgeführten Vorgänge einer MetroCluster-Konfiguration abrufen. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.MetroCluster SVMs
Sie können Informationen zu allen SVM-Paaren in einer MetroCluster-Konfiguration abrufen. Dieser Ressourcentyp wurde mit ONTAP 9.11.1 eingeführt.

.Knoten
ONTAP Cluster bestehen aus einem oder mehreren Nodes. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt und mit ONTAP 9.8 aktualisiert.

.NTP-Schlüssel
Das Network Time Protocol (NTP) kann so konfiguriert werden, dass es freigegebene private Schlüssel zwischen ONTAP und vertrauenswürdigen externen NTP-Zeitservern verwendet. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

.NTP-Server
Mit diesen API-Aufrufen können Sie die Einstellungen für das ONTAP-Netzwerkzeitprotokoll konfigurieren, einschließlich der externen NTP-Server und -Schlüssel. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

.Kollegen
Die Peer-Objekte repräsentieren Endpunkte und unterstützen die Cluster-Peering-Beziehungen. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Performance-Zähler
Frühere ONTAP-Releases haben statistische Informationen über die betrieblichen Eigenschaften des Systems erhalten. In der Version 9.11.1 wurden die Informationen verbessert und sind nun über DIE REST API verfügbar. Diese Funktion bringt das ONTAP REST API näher an Parität mit dem Data ONTAP API (ONTAPI oder ZAPI). Dieser Ressourcentyp wurde mit ONTAP 9.11 eingeführt.

.Ressourcen-Tags
Sie können Tags verwenden, um REST-API-Ressourcen zu gruppieren. Auf diese Weise können Sie verwandte Ressourcen innerhalb eines bestimmten Projekts oder einer bestimmten Organisationsgruppe zuordnen. Mithilfe von Tags können Sie Ressourcen effektiver organisieren und verfolgen. Dieser Ressourcentyp wurde mit ONTAP 9.13 eingeführt.

.Zeitpläne
Zeitpläne können zur Automatisierung der Aufgabenstellungen genutzt werden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Sensoren
Über diese Endpunkte können Sie Details zu allen Umgebungssensoren der Plattform abrufen. Dieser Ressourcentyp wurde mit ONTAP 9.11 eingeführt.

.Software
Ein ONTAP Cluster umfasst das Cluster-Softwareprofil, die Erfassung von Softwarepaketen und die Erfassung des Software-Verlaufs. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt und mit ONTAP 9.8 aktualisiert.

.Web
Sie können diese Endpunkte verwenden, um die Webservices-Konfigurationen zu aktualisieren und die aktuelle Konfiguration abzurufen. Dieser Ressourcentyp wurde mit ONTAP 9.10 eingeführt.
