---
sidebar: sidebar 
permalink: resources/san.html 
keywords: san resources 
summary: Sie können diese API-Aufrufe für das Management von SAN-Ressourcen verwenden. 
---
= San
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können diese API-Aufrufe für das Management von SAN-Ressourcen (Storage Area Networking) verwenden.

.Fibre Channel-Anmeldungen
Fibre Channel-Anmeldungen stellen Verbindungen dar, die von Fibre Channel-Initiatoren gebildet wurden, die bei ONTAP angemeldet sind. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Fibre Channel Protocol Services
Ein Fibre Channel Protocol (FCP)-Service definiert die Eigenschaften eines Fibre Channel-Ziels für eine SVM. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt und mit ONTAP 9.7 aktualisiert. Die Unterstützung für das Abrufen von Performance-Kennzahlen-Daten wurde mit ONTAP 9.14 hinzugefügt.

.Fibre Channel WWPN-Aliase
Ein der World Wide Port Name (WWPN) ist ein 64-bit-Wert, der einen Fibre Channel-Port eindeutig identifiziert. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.igroups
Eine Initiatorgruppe ist eine Sammlung von Fibre Channel-WWPNs (World Wide Port Names) und iSCSI IQNs (qualifizierte Namen) und iSCSI EUIs (Extended Unique Identifier), die Host-Initiatoren identifizieren. Dieser Ressourcentyp wurde ursprünglich mit ONTAP 9.6 eingeführt.

Geschachtelte Initiatorgruppen ist eine neue Funktion von ONTAP 9.9. Zudem wurde die REST-API unterstützt. Dieser REST-Ressourcentyp wurde mit ONTAP 9.9 eingeführt.

.Initiatoren
Ein Initiator ist ein Fibre Channel (FC) World Wide Port Name (WWPN), ein iSCSI Qualified Name (IQN) oder ein iSCSI EUI (Extended Unique Identifier), der einen Host-Endpunkt identifiziert. Sie können Initiatoren für das Cluster oder eine bestimmte SVM abrufen. Dieser Ressourcentyp wurde mit ONTAP 9.14 eingeführt.

.ISCSI-Anmeldedaten
Das iSCSI-Anmeldeinformationen-Objekt enthält Authentifizierungsdaten, die von einem Initiator und ONTAP verwendet werden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.ISCSI-Services
Ein iSCSI-Service definiert die Eigenschaften des iSCSI-Ziels für eine SVM. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt und mit ONTAP 9.7 aktualisiert. Die Unterstützung für das Abrufen von Performance-Kennzahlen-Daten wurde mit ONTAP 9.14 hinzugefügt.

.ISCSI-Sitzungen
Eine iSCSI-Sitzung ist eine oder mehrere TCP-Verbindungen, die einen iSCSI-Initiator mit einem iSCSI-Ziel verbinden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.LUN-Attribute
LUN-Attribute sind aufruferdefinierte Name-/Wertpaare, die optional mit einer LUN gespeichert werden können. Diese Attribute können zur Speicherung kleiner Mengen applikationsspezifischer Metadaten verwendet und werden nicht von ONTAP interpretiert. Mit den Endpunkten können Sie Attribute für eine LUN erstellen, aktualisieren, löschen und erkennen. Dieser Ressourcentyp wurde mit ONTAP 9.10 eingeführt.

.LUN-Zuordnungen
Eine LUN-Zuordnung ist eine Zuordnung zwischen einer LUN und einer Initiatorgruppe. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.LUN ordnet den Knoten für die Berichterstellung zu
Die Knoten zur Berichterstellung sind die Cluster Nodes, von denen Netzwerkpfade zu einer zugeordneten LUN mithilfe der SAN-Protokolle als Teil der Selective LUN Map (SLM)-Funktion von ONTAP angekündigt werden. Mit den neuen Endpunkten können die Reporting-Nodes einer LUN-Zuordnung hinzugefügt, entfernt und ermittelt werden. Dieser Ressourcentyp wurde mit ONTAP 9.10 eingeführt.

.LUNs
Eine LUN ist die logische Darstellung des Storage in einem Storage Area Network (SAN). Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt und mit ONTAP 9.7 aktualisiert. Die Unterstützung für das Abrufen von Performance-Kennzahlen-Daten wurde mit ONTAP 9.14 hinzugefügt.

.Port-Sets
Ein Portsatz ist eine Sammlung von Fibre Channel- oder iSCSI-Netzwerkschnittstellen, die der Storage VM „_portset_“ zugeordnet sind. Während diese Funktion für frühere Versionen von ONTAP vorhanden war, wurde jetzt auch der REST API Support hinzugefügt. Dieser REST-Ressourcentyp wurde mit ONTAP 9.9 eingeführt.

.VVol Bindungen
Ein VMware Virtual Volume (vVol) Bindung ist eine Verknüpfung zwischen einer LUN der Klasse `protocol_endpoint` Und eine LUN der Klasse `vvol`. Mit der vVol Binding REST API können Sie vVol Bindungen erstellen, löschen und entdecken. Dieser Ressourcentyp wurde mit ONTAP 9.10 eingeführt.
