---
sidebar: sidebar 
permalink: resources/security.html 
keywords:  
summary:  
---
= Sicherheit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können diese API-Aufrufe verwenden, um die Sicherheitseinstellungen für das Cluster und SVM zu verwalten.

.Konten
Es gibt eine Sammlung von Benutzerkonten für das Cluster und SVMs. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Kontobezeichnung
Konfiguration für ein Scoped-Benutzerkonto. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Active Directory-Proxy
Sie können die SVM-Kontoinformationen auf dem Active Directory-Server verwalten. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

.Ransomware schützen
ONTAP erkennt Dateien, die möglicherweise eine Ransomware-Bedrohung enthalten. Es gibt mehrere Endgeräte-Kategorien. Sie können eine Liste dieser verdächtigen Dateien abrufen oder von einem Volume entfernen. Dieser Ressourcentyp wurde mit ONTAP 9.10.1 eingeführt. Unterstützung für die Anzeige der Version und die Aktualisierung des Anti-Ransomware-Pakets wurde mit ONTAP 9.16 hinzugefügt.

.Prüfung
Die Einstellungen, die bestimmen, was in den Audit-Log-Dateien protokolliert wird. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Audit-Ziele
Diese Einstellungen steuern, wie Audit-Log-Informationen an Remote-Systeme oder splunk Server übermittelt werden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Audit-Meldungen
Sie können die Meldungen des Prüfprotokolls abrufen. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.AWS KMS
Amazon Web Services umfasst einen Verschlüsselungsmanagement-Service, der sicheren Storage für Schlüssel und andere Geheimnisse bietet. Sie können über die REST-API auf diesen Service zugreifen, sodass ONTAP seine Schlüssel sicher in der Cloud speichern kann. Darüber hinaus können Sie die mit NetApp Storage Encryption verwendeten Authentifizierungsschlüssel erstellen und auflisten. Diese Unterstützung ist in ONTAP 9.12 neu.

.Azure Key Vault
Bei diesem Satz von API-Aufrufen können Sie Azure Schlüsselspeicher verwenden, um die ONTAP-Verschlüsselungsschlüssel zu speichern. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.Zertifikate
Mit den API-Aufrufen können von ONTAP verwendete Zertifikate installiert, angezeigt und gelöscht werden. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

.Cisco Duo
Duo bietet zwei-Faktor-Authentifizierung für SSH-Anmeldungen. Sie können Duo für den Betrieb auf ONTAP-Cluster- oder SVM-Ebene konfigurieren. Dieser Ressourcentyp wurde mit ONTAP 9.14 eingeführt.

.Cluster-Sicherheit
Sie können Details zur Cluster-weiten Sicherheit abrufen und bestimmte Parameter aktualisieren. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt und mit ONTAP 9.8 aktualisiert.

.Externe Rollen
Eine externe Rolle wird bei einem OAUTH 2.0-Ident-Provider definiert. Sie können Zuordnungsbeziehungen zwischen diesen externen Rollen und den ONTAP Rollen erstellen und verwalten. Dieser Ressourcentyp wurde mit ONTAP 9.16 eingeführt.

.GCP-KMS
Mit diesem Satz von API-Aufrufen können Sie den Google Cloud Platform Key Management Service zum Speichern und Verwalten der ONTAP-Verschlüsselungsschlüssel verwenden. Dieser Ressourcentyp wurde zunächst mit der ONTAP 9.8 REST-API eingeführt. Diese Funktion wurde jedoch neu gestaltet und gilt bei neuen Ressourcentypen in ONTAP 9.9 als neu.

.Gruppen
Sie können Gruppenkonfigurationen verwalten, einschließlich Gruppen, die mit UUIDs dargestellt werden. Dieser Ressourcentyp wurde mit ONTAP 9.16 eingeführt.

.Gruppenrollenzuordnungen
Sie können Zuordnungsbeziehungen zwischen Gruppen und Rollen erstellen und verwalten. Dieser Ressourcentyp wurde mit ONTAP 9.16 eingeführt.

.IPsec
Internet Protocol Security (IPSec) ist eine Protokollsuite, die Sicherheit zwischen zwei Endpunkten über ein zugrunde liegendes IP-Netzwerk bietet. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.IPsec CA-Zertifikate
Sie können IPSec-CA-Zertifikate hinzufügen, entfernen und abrufen. Dieser Ressourcentyp ist neu in ONTAP 9.10.

.IPsec-Richtlinien
Mit diesem Satz von API-Aufrufen können Sie die für eine IPSec-Bereitstellung geltenden Richtlinien verwalten. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.IPsec-Sicherheitszuordnungen
Sie können diesen Satz von API-Aufrufen verwenden, um die für eine IPSec-Bereitstellung relevanten Sicherheitszuordnungen zu verwalten. Dieser Ressourcentyp ist neu in ONTAP 9.8.

.Konfiguration für Schlüsselmanager
Mit diesen Endpunkten können Sie die Konfigurationen für Schlüsselmanager abrufen und aktualisieren. Dieser Ressourcentyp ist neu in ONTAP 9.10.

.Schlüsselmanager
Ein Schlüsselmanager erlaubt Client-Modulen innerhalb von ONTAP, sicher gespeicherte Schlüssel zu speichern. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt und für ONTAP 9.7 aktualisiert. Ein weiteres Update mit ONTAP 9.12 zur Unterstützung der Authentifizierungsschlüssel war vorhanden. In ONTAP 9.13 wurde eine Wiederherstellungsfunktion hinzugefügt.

.Schlüsselspeicher
Ein Schlüsselspeicher beschreibt den Typ eines Schlüsselmanagers. Dieser Ressourcentyp ist neu in ONTAP 9.10. Weitere Endpunkte, die eine verbesserte Steuerung unterstützen, wurden mit ONTAP 9.14 hinzugefügt.

.LDAP-Authentifizierung
Diese API-Aufrufe werden zum Abrufen und Verwalten der Cluster-LDAP-Serverkonfiguration verwendet. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Anmeldungsmeldungen
Wird zum Anzeigen und Verwalten der von ONTAP verwendeten Login-Meldungen verwendet. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Verifizierung mehrerer Administratoren
Die Überprüfungsfunktion für mehrere Administratoren stellt ein flexibles Autorisierungs-Framework zum Schutz des Zugriffs auf ONTAP-Befehle oder -Vorgänge bereit. Es gibt 17 neue Endpunkte, die das Definieren, anfordern und Genehmigen von Zugriff in den folgenden Bereichen unterstützen:

* Regeln
* Anträge
* Genehmigungsgruppen


Wenn mehrere Administratoren Zugriff genehmigen können, lässt sich die Sicherheit Ihrer ONTAP- und IT-Umgebungen verbessern. Diese Ressourcentypen wurden mit ONTAP 9.11 eingeführt.

.NIS-Authentifizierung
Diese Einstellungen werden zum Abrufen und Verwalten der NIS-Serverkonfiguration des Clusters verwendet. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.OAuth 2.0
Open Authorization (OAuth 2.0) ist ein Token-basiertes Framework, mit dem der Zugriff auf Ihre ONTAP Storage-Ressourcen eingeschränkt werden kann. Sie können sie zusammen mit Clients verwenden, die über die REST-API auf ONTAP zugreifen. Dieser Ressourcentyp wurde mit ONTAP 9.14 eingeführt. Es wurde durch die Unterstützung des Microsoft Entra ID Autorisierungsservers (ehemals Azure AD) mit Standard-OAuth 2.0-Ansprüchen um ONTAP 9.16 erweitert. Darüber hinaus werden die Entra ID-Standardgruppen-Ansprüche auf Basis von UUID-Stilwerten durch neue Gruppen- und Rollenzuordnungsfunktionen unterstützt. Eine neue externe Rollenzuordnung wurde ebenfalls eingeführt. Siehe auch *Externe Rollen*, *Gruppen* und *Gruppen-Rollenzuordnungen*.

.Passwortrauthentifizierung
Dazu gehört auch der API-Aufruf, der zum Ändern des Kennworts eines Benutzerkontos verwendet wird. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Berechtigungen für eine Rolleninstanz
Verwalten Sie die Berechtigungen für eine bestimmte Rolle. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Authentifizierung über öffentlichen Schlüssel
Sie können diese API-Aufrufe verwenden, um die öffentlichen Schlüssel für Benutzerkonten zu konfigurieren. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

.Rollen
Die Rollen bieten eine Möglichkeit, Benutzerkonten Berechtigungen zuzuweisen. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.Instanz Rollen
Spezifische Instanz einer Rolle. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.SAML-Service-Provider
Sie können die Konfiguration für den SAML-Dienstanbieter anzeigen und verwalten. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

.SSH
Mit diesen Aufrufen können Sie die SSH-Konfiguration festlegen. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

.SSH SVMs
Mit diesen Endpunkten können Sie die SSH-Sicherheitskonfiguration für alle SVMs abrufen. Dieser Ressourcentyp wurde mit ONTAP 9.10 eingeführt.

.TOTPS
Sie können die REST-API verwenden, um zeitbasierte TOTP-Profile (One-Time Password) für Konten zu konfigurieren, die sich über SSH anmelden und auf ONTAP zugreifen. Dieser Ressourcentyp wurde mit ONTAP 9.13 eingeführt.

.Web-Authentifizierung
Web Authentication (WebAuthn) ist ein Webstandard für die sichere Authentifizierung von Benutzern basierend auf Public Key-Kryptographie. Mit ONTAP unterstützt es die Administration von Phishing-resistenten MFAs über System Manager und die ONTAP REST API. Diese Funktion wurde mit ONTAP 9.16 hinzugefügt.
