---
sidebar: sidebar 
permalink: resources/support.html 
keywords: support resources 
summary: Sie können diese API-Aufrufe verwenden, um die ONTAP-Funktionen zu verwalten, die zur Unterstützung eines Clusters verwendet werden. 
---
= Unterstützung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können diese API-Aufrufe verwenden, um die ONTAP-Funktionen zu verwalten, die zur Unterstützung eines Clusters verwendet werden.

Eine eigenständige Anwendung kann EMS-Ereignisse und optional generierte AutoSupport-Pakete bei einem ONTAP-System durch Ausgabe einer POST-Anfrage aufzeichnen. Dieser Ressourcentyp wurde mit ONTAP 9.11.1 eingeführt

Mit der automatischen Aktualisierungsfunktion bleiben Ihre ONTAP-Systeme auf dem Laufenden, indem Sie die neuesten Software-Updates herunterladen und anwenden. Es gibt verschiedene Endpunktkategorien zur Unterstützung der Funktion, einschließlich Status, Konfiguration und Updates. Diese Ressourcentypen wurden mit ONTAP 9.10 eingeführt.

AutoSupport sammelt Konfigurations- und Statusdetails sowie Fehler und meldet die Informationen an NetApp. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Jeder Node behält AutoSupport Meldungen, die generiert und abgerufen werden können. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Mit diesen APIs können Sie die aktuellen Backup-Einstellungen abrufen und aktualisieren. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Sie können Backup-Dateien der Konfiguration erstellen, abrufen und löschen. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

Mithilfe dieser Endpunkte können Sie die von einem Cluster oder Node generierten Memory Core Dumps abrufen und verwalten. Dieser Ressourcentyp wurde mit ONTAP 9.10 eingeführt.

Das Event Management System (EMS) sammelt Ereignisse und sendet Benachrichtigungen an ein oder mehrere Ziele. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Die EMS-Ziele bestimmen, wie und wo Benachrichtigungen gesendet werden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Eine EMS-Zielinstanz ist nach Typ und Standort definiert. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Dies ist eine Live-Sammlung von Systemereignissen für den Cluster. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Die EMS-Filter identifizieren gemeinsam die Ereignisse, die eine zusätzliche Bearbeitung erfordern. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Eine EMS-Filterinstanz ist eine Sammlung von Regeln, die auf die Ereignisse angewendet werden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Bietet Zugriff auf den EMS-Ereigniskatalog. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Für eine bestimmte Instanz eines EMS-Filters kann eine Liste von Regeln verwaltet werden. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Eine einzelne Regel für eine bestimmte Instanz eines EMS-Filters. Dieser Ressourcentyp wurde mit ONTAP 9.6 eingeführt.

Sie können SNMP- und Trap-Vorgänge für das Cluster aktivieren und deaktivieren. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

Ein SNMP-Trap-Host ist ein System, das für den Empfang von SNMP-Traps von ONTAP konfiguriert ist. Sie können die Hosts abrufen und definieren. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

Sie können bestimmte SNMP-Trap-Hosts verwalten. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

Sie können SNMP-Benutzer definieren und verwalten. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.

Sie können einen bestimmten SNMP-Benutzer verwalten, wobei die Engine-ID der administrativen SVM oder der Daten-SVM zugeordnet ist. Dieser Ressourcentyp wurde mit ONTAP 9.7 eingeführt.
