---
sidebar: sidebar 
permalink: migrate/blogs_migrate.html 
keywords: blogs, blog articles 
summary: Es gibt mehrere Blog-Artikel, die Ihnen dabei helfen, besser zu verstehen, wie Sie von ONTAPI auf die ONTAP REST API migrieren. 
---
= Blog-Artikel
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es gibt mehrere Blog-Artikel, die Ihnen dabei helfen, besser zu verstehen, wie Sie von ONTAPI auf die ONTAP REST API migrieren.

.ONTAPI zu REST Mapping
NetApp bietet Unterstützung beim Wechsel von der proprietären ONTAPI API API zur ONTAP REST API durch Mapping-Dokumentation.

https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["netapp.io/2020/12/17/ontapi-zu-Rest-Zuordnung"^]

.Umwandlung Ihrer Automatisierung in eine ONTAP REST-API von ONTAPI
Es stehen verschiedene Technologien zur Verfügung, mit denen Sie Ihre ONTAP-Automatisierungsumgebung auf Basis der REST-API transformieren können.

https://www.netapp.com/blog/transform-automation-ontap-rest-api/["www.netapp.com/blog/transform-automation-ontap-rest-api"^]

.Verwenden des privaten CLI-Passthrough mit der ONTAP REST API
Damit CLI- und ONTAP-Benutzer die Transition auf die ONTAP REST API erleichtern, bietet ONTAP einen privaten REST-API-Endpunkt, über den auf jeden CLI-Befehl zugegriffen werden kann.

https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api"^]

.Wechsel von ONTAPI mithilfe des ONTAPI Usage Reporting Tools
NetApp bietet ein Tool, das Kunden und Partner beim Wechsel zur ONTAP REST API unterstützt.

https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["netapp.io/2022/03/21/Transition-from-ontapizapi-using-ontapi-Usage-Reporting-Tool"^]
