---
sidebar: sidebar 
permalink: migrate/migration-considerations.html 
keywords: migrate, mirgate to rest api, snapdiff 
summary: 'Vor der Migration zur ONTAP-REST-API von entweder der ONTAPI (ZAPI) oder der ONTAP-CLI sollten Sie mehrere Probleme in Betracht ziehen.' 
---
= Migrationsüberlegungen für die ONTAP-REST-API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die ONTAPI API (ZAPI) ist der ursprüngliche Satz proprietärer Aufrufe, die in der NetApp ONTAP -Software enthalten sind.  Die API wird über das Network Manageability SDK bereitgestellt und unterstützt die Automatisierung von Datenspeicherverwaltungs- und -managementaufgaben.  Wenn Sie ONTAPI verwenden, sollten Sie Ihre Migration zur ONTAP REST API planen, um die erweiterten ONTAP -Funktionen zu nutzen, die mit der REST API verfügbar sind.



[[general-design-differences]]
== Allgemeine Designunterschiede

Die ONTAP REST API und die Befehlszeilenschnittstelle haben ein grundlegend anderes Design. Die CLI-Befehle und -Parameter werden den REST-API-Aufrufen nicht direkt zugeordnet. Und auch wenn es eine Ähnlichkeit geben könnte, können die Details der Eingabeparameter unterschiedlich sein. Beispielsweise können numerische Einheiten in Byte oder mit einem Suffix (z. B. KB) angegeben werden. Siehe link:../rest/input_variables.html["Eingabevariablen, die eine API-Anforderung steuern"] Und link:../reference/api_reference.html["API-Referenz"] Finden Sie weitere Informationen.



[[data-svms-exposed-through-the-rest-api]]
== Data-SVMs werden über DIE REST-API offengelegt

ONTAP unterstützt mehrere Arten von Storage Virtual Machines (SVMs). Allerdings sind nur die Daten-SVMs direkt über die ONTAP REST API zugänglich. Die Konfigurationsinformationen, die das Cluster und die Nodes beschreiben, sind über die REST-API verfügbar. Das Cluster und die Nodes werden jedoch nicht als separate SVMs behandelt.



[[access-the-ontap-cli-through-the-rest-api]]
== Greifen Sie über die REST API auf die ONTAP-CLI zu

ONTAP bietet einen REST-Endpunkt für den Zugriff auf die ONTAP-CLI, um die ONTAPI und CLI-Benutzer bei der Transition zur ONTAP-REST-API zu unterstützen. Sie können diese Passthrough-Funktion verwenden, um jeden CLI-Befehl auszuführen.  Die Nutzung des REST-Endpunkts wird in den AutoSupport-Daten zurückgegeben, damit NetApp Lücken in der REST-API identifizieren und in künftigen ONTAP-Versionen Verbesserungen vornehmen kann.

Um einen CLI-Befehl auszustellen, müssen Sie einen REST API-Aufruf machen, der ordnungsgemäß basierend auf Regeln bezüglich folgender Punkte gebildet wird:

* Ressourcenpfade
* Feldnamen
* HTTP-Methoden


Der grundlegende Ressourcenpfad für CLI-Zugriff ist `/private/cli`. Informationen zum Zugriff auf die CLI über DIE REST-API finden Sie auf der ONTAP-API-Seite mit der Online-Dokumentation. NetApp unterhält zudem ein GitHub-Repository mit Codebeispielen und anderen nützlichen Informationen. Siehe https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["ONTAP REST Python GitHub-Repository - CLI-Passthrough-Samples"^] Finden Sie weitere Informationen.



[[changes-to-snapdiff-availability-in-ontapi]]
== Änderungen an der SnapDiff Availability in ONTAPI

SnapDiff v1 und v2 basieren auf dem ONTAPI (ZAPI) Management-Framework und es gibt einige Nutzungsbeschränkungen mit bestimmten Versionen von ONTAP. Die SnapDiff v3 API verwendet kein ONTAPI und wird mit ONTAP 9.8 und neueren Versionen unterstützt. Die SnapDiff API-Verfügbarkeit über ONTAP Versionen hinweg ist wie folgt definiert:

* ONTAP 9.7 und frühere Versionen: v1 und v2 (nur ONTAPI)
* ONTAP 9.8 und spätere Versionen: v1, v2 und v3. Einige Einschränkungen gelten; siehe das  https://kb.netapp.com/on-prem/ontap/DP/SnapDiff/SnapDiff-KBs/FAQ_SnapDiff_Support_in_ONTAP["Häufig gestellte Fragen: SnapDiff Unterstützung in ONTAP"^] für weitere Details zur SnapDiff-Unterstützung abhängig von der ONTAP Version.


Es sollte überprüft werden, ob Ihre Backup-Anwendungen SnapDiff unterstützen und ob Einschränkungen bei der Interoperabilität in Abhängigkeit von der verwendeten ONTAP Version bestehen. Siehe auch die https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP"^] für weitere Informationen.



[[related-information]]
== Verwandte Informationen

* link:../get-started/ontap_automation_options.html["ONTAP-Automatisierungsoptionen"]
* https://mysupport.netapp.com/info/communications/ECMLP2880232.html["CPC-00410 Deferral of ONTAPI (ZAPI) – Ankündigung der Einstellung des Service"^]
* https://kb.netapp.com/onprem/ontap/dm/REST_API/FAQs_on_ZAPI_to_ONTAP_REST_API_transformation_for_CPC_(Customer_Product_Communiques)_notification["FAQs zur ZAPI-zu-ONTAP-REST-API-Transformation für CPC"^]
* https://kb.netapp.com/on-prem/ontap/DP/SnapDiff/SnapDiff-KBs/FAQ_SnapDiff_Support_in_ONTAP["Häufig gestellte Fragen: SnapDiff Unterstützung in ONTAP"^]

