---
sidebar: sidebar 
permalink: migrate/software.html 
keywords:  
summary:  
---
= Tools und Software, die die ONTAP REST API unterstützen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp bietet Beispiel-Python-Skripts und andere damit verbundene Software zur Unterstützung Ihrer Migration von ONTAP zur ONTAP REST-API. Die wichtigsten dieser Proben werden im Folgenden beschrieben.


NOTE: Alle Python-Codebeispiele sind im GitHub-Repository verfügbar https://github.com/NetApp/ontap-rest-python["NetApp ONTAP REST Python"^]. Lesen Sie auch die Ressourcen, die in verfügbar sindlink:../additional/learn_more.html["Weitere Informationen zur REST-API von ONTAP"].



== ONTAPI Tool zur Berichterstellung zur Nutzung

Das ONTAPI Tool zur Nutzungsberichterstellung soll NetApp Professional Services, Kunden und Partner bei der Identifizierung der ONTAPI-Nutzung in ihrer ONTAP Umgebung unterstützen. Skripts werden für drei verschiedene Anwendungsfälle bereitgestellt, wie in der folgenden Tabelle beschrieben.

[cols="20,80"]
|===
| Skript | Beschreibung 


| apache_scraper.py | Ein Apache-Protokollabstreifer, um die ONTAPI-Aufrufe zu finden, die für die ONTAP-Knoten ausgegeben werden 


| session_stats.py | Ein CLI-Skript zum Abrufen von Sitzungsstatistikdaten aus ONTAP 


| zapi_to_rest.py | Ein Skript, um die RESTLICHEN Details der ONTAPI-Aufrufe und übergebenen Attribute zu extrahieren 
|===
Sie können auf das zugreifen https://github.com/NetApp/ontap-rest-python/tree/master/ONTAPI-Usage-Reporting-Tool["ONTAPI Tool zur Berichterstellung zur Nutzung"^] Und legen Sie los. Siehe auch A https://www.youtube.com/watch?v=gJSWerW9S7o["Demo"^] Das Reporting-Tool und seine Verwendung.



== Private CLI-Passthrough

Die REST-API bietet umfassende Abdeckung der Funktionen und Einrichtungen von ONTAP. Es kann jedoch vorkommen, dass ein direkter Zugriff über die REST-API auf die ONTAP-CLI nützlich sein kann.

Eine Einführung zu dieser Funktion finden Sie unter link:../rest/access_ontap_cli.html["Greifen Sie über die REST API auf die ONTAP-CLI zu"]. Für die Python-Beispiele siehe https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["REST CLI-Passthrough-Beispiele"^].



== Python-Client-Bibliothek

Die Python-Client-Bibliothek ist ein Paket, das Sie installieren und verwenden können, um auf die ONTAP-REST-API mit Python zuzugreifen. Mit ihr können Sie schnell und robusten Code für die Automatisierung Ihrer ONTAP Implementierungen entwickeln. Weitere Informationen über die Python-Client-Bibliothek finden Sie unter link:../python/learn-about-pcl.html["Python-Client-Bibliothek"].



== ONTAP PowerShell Toolkit

Das NetApp.ONTAP PowerShell Toolkit erweitert Ihre lokale PowerShell Umgebung um ein Modul mit mehr als 2,400 Commandlets. Damit können Sie schnell Code für Ihren Windows-Host entwickeln und die ONTAP-Bereitstellungen automatisieren. Weitere Informationen finden Sie unter link:../pstk/overview_pstk.html["Überblick über das PowerShell Toolkit"].
