---
sidebar: sidebar 
permalink: migrate/software.html 
keywords:  
summary:  
---
= Tools und Software von NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp bietet Beispiel-Python-Skripts und andere damit verbundene Software zur Unterstützung Ihrer Migration von ONTAP zur ONTAP REST-API. Die wichtigsten dieser Proben werden im Folgenden beschrieben.


NOTE: Alle Python-Codebeispiele sind auf der verfügbar https://github.com/NetApp/ontap-rest-python["NetApp ONTAP REST Python"^] GitHub Repository:

.ONTAPI Tool zur Berichterstellung zur Nutzung
Das ONTAPI Tool zur Nutzungsberichterstellung soll NetApp Professional Services, Kunden und Partner bei der Identifizierung der ONTAPI-Nutzung in ihrer ONTAP Umgebung unterstützen. Skripts werden für drei verschiedene Anwendungsfälle bereitgestellt, wie in der folgenden Tabelle beschrieben.

[cols="20,80"]
|===
| Skript | Beschreibung 


| apache_scraper.py | Ein Apache-Protokollabstreifer, um die ONTAPI-Aufrufe zu finden, die für die ONTAP-Knoten ausgegeben werden 


| session_stats.py | Ein CLI-Skript zum Abrufen von Sitzungsstatistikdaten aus ONTAP 


| zapi_to_rest.py | Ein Skript, um die RESTLICHEN Details der ONTAPI-Aufrufe und übergebenen Attribute zu extrahieren 
|===
Siehe https://github.com/NetApp/ontap-rest-python/tree/master/ONTAPI-Usage-Reporting-Tool["ONTAPI Tool zur Berichterstellung zur Nutzung"^] Finden Sie weitere Informationen.

.Private CLI-Passthrough
Die REST-API bietet umfassende Abdeckung der Funktionen und Einrichtungen von ONTAP. Es kann jedoch vorkommen, dass ein direkter Zugriff über die REST-API auf die ONTAP-CLI nützlich sein kann.

Eine Einführung zu dieser Funktion finden Sie unter link:../rest/access_ontap_cli.html["Greifen Sie über die REST API auf die ONTAP-CLI zu"]. Für die Python-Beispiele siehe https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["REST CLI-Passthrough-Beispiele"^].

.Python-Client-Bibliothek
Die Python-Client-Bibliothek ist ein Paket, das Sie installieren und verwenden können, um auf die ONTAP-REST-API mit Python zuzugreifen. Mit ihr können Sie schnell und robusten Code für die Automatisierung Ihrer ONTAP Implementierungen entwickeln.

Eine Einführung in die Python Client-Bibliothek finden Sie unter link:../python/overview_pcl.html["Überblick über die Python Client Library"]. Für die Python-Beispiele siehe https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["Beispiele für Python Client-Bibliotheken"^].
