---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: Zudem stehen Ihnen mehrere weitere Ressourcen zur Verfügung, die Ihnen helfen. Dort erhalten Sie weitere Informationen zur Automatisierung der Implementierung und Administration Ihrer ONTAP Storage-Systeme. 
---
= Weitere Informationen zur REST-API von ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es stehen verschiedene zusätzliche Ressourcen zur Verfügung, die Sie bei der Automatisierung der Implementierung und Administration Ihrer ONTAP Storage-Systeme unterstützen.



== Blog-Artikel

Die Blog-Artikel sind in mehreren Abschnitten auf der Grundlage des Themas angeordnet.



=== Allgemein

* Eine gute Zusammenfassung der aktuellen Automatisierungstechnologien von ONTAP.
+
https://www.netapp.com/blog/new-normal-for-automation["Neue Normalität für die Automatisierung"^]

* Sie können ONTAP-Ereignisse überwachen, um stets über die Systemaktivität informiert zu bleiben. Die Konfiguration und das Management dieser Ereignisse können mit der REST-API automatisiert werden.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["ONTAP REST-APIs: Automatische Benachrichtigung über Ereignisse hoher Schweregrad"^]

* Kaffeepausen mit RUHE (6 Episoden):
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["Grundlagen der ONTAP REST-APIs"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["Funktionen von ONTAP REST-APIs"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["Praktische Erfahrungen mit ONTAP REST mit Postman"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["ONTAPI (ZAPI) Reporting-Tool"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["Private CLI-Passthrough"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["5 magische Funktionen, die die ONTAP Storage-Automatisierung vereinfachen!"^]






=== Python-Client-Bibliothek

* Dieser Blog bietet eine gute Einführung in die Funktionen der ONTAP Python Client Library.
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["Vereinfachte ONTAP-REST-API-Nutzung mit der Python Client Library"^]





=== Migration zur REST-API

* Es stehen verschiedene Technologien zur Verfügung, mit denen Sie Ihre ONTAP-Automatisierungsumgebung auf Basis der REST-API transformieren können.
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["Umwandlung Ihrer Automatisierung in eine ONTAP REST-API von ONTAPI"^]





== Videos

* Eine gute Einführung in die NetApp Python Client Bibliothek und wie man mit dem Schreiben von Code über die Bibliothek beginnt.
+
video::pg5ls1Ol6uw[youtube,width=848,height=480]
* Ansible-zertifizierte Module:
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Eine Sammlung von Videos bei NetApp TechComm TV.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["Automatisieren Sie das NetApp ONTAP Management"^]





== NetApp Knowledge Base

* Wenn Sie ein Problem mit der ONTAP REST-API haben, können Sie es NetApp melden.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["So melden Sie Probleme auf der ONTAP REST API und der ONTAP REST API Python Client-Bibliothek"^]

* Wenn Sie eine funktionale Lücke in der ONTAP-REST-API identifizieren, können Sie eine neue Funktion für die API anfordern.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["Anfordern einer Funktion für die ONTAP-REST-API"^]


