---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: Zudem stehen Ihnen mehrere weitere Ressourcen zur Verfügung, die Ihnen helfen. Dort erhalten Sie weitere Informationen zur Automatisierung der Implementierung und Administration Ihrer ONTAP Storage-Systeme. 
---
= Weitere Ressourcen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es stehen verschiedene zusätzliche Ressourcen zur Verfügung, die Sie bei der Automatisierung der Implementierung und Administration Ihrer ONTAP Storage-Systeme unterstützen.



== ONTAP 9 – Ressourcen

* Enthält Dokumentation für die ONTAP 9 Produktfamilie.
+
https://docs.netapp.com/us-en/ontap-family/["Produktdokumentation zu ONTAP 9"^]

* Versionshinweise zu ONTAP 9 mit Informationen zum aktuellen Release.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP"^]

* Umfasst die Dokumentation und andere hilfreiche Links für Planung, Administration und Support von ONTAP 9.
+
https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["ONTAP- und ONTAP System Manager-Ressourcen"^]

* Lesen Sie die Versionshinweise und andere Dokumente zu früheren ONTAP Versionen.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 Produktbibliothek"^]





== ONTAP 9 Entwicklerressourcen

* Unterstützung beim Einstieg in Ansible in einer DevOps-Umgebung
+
https://www.netapp.com/devops-solutions/ansible/["NetApp Ansible DevOps-Lösungen"^]

* Bietet die wichtigsten ONTAPI-Aufrufe und eine Zuordnung zu den entsprechenden REST-API-Aufrufen. Wählen Sie die entsprechende ONTAP-Version aus.
+
link:../migrate/mapping.html["ONTAPI-to-REST-API-Zuordnung"]

* Das Paket der NetApp Python Client Library bei PyPI.
+
https://pypi.org/project/netapp-ontap["PyPI: NetApp ONTAP"^]

* Dokumentation für die NetApp Python Client Library.
+
https://library.netapp.com/ecmdocs/ECMLP2886776/html/index.html["NetApp PCL-Dokumentation für 9.14.1"^]

* Stellt Ressourcen und Dokumentation bereit, die für die Verwendung der ONTAP-REST-API erforderlich sind.
+
https://devnet.netapp.com/restapi.php["NetApp Entwicklernetzwerk: ONTAP RESTful API"^]





== Blog-Artikel

* Das CLI-Passthrough bietet eine Technik zum Ausführen von ONTAP-CLI-Befehlen unter Verwendung der REST-API.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api["Verwenden des privaten CLI-Passthrough mit der ONTAP REST API"^]

* Neu bei Ansible zur ONTAP-Automatisierung:
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible["Erste Schritte mit NetApp und Ansible – Installation von Ansible"^]





== Videos

* Eine gute Einführung in die NetApp Python Client Bibliothek und wie man mit dem Schreiben von Code über die Bibliothek beginnt.
+
https://www.youtube.com/watch?v=Wws3SB5d9Ss["Erste Schritte mit der NetApp ONTAP Python Client Library"^]

* Dieses Video ist auch über NetApp TV unter verfügbar link:https://tv.netapp.com/detail/video/6217195551001["Ansible-Zertifizierte Module"^].
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Ansible-zertifizierte Module:
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]




== NetApp Ressourcen

* Sie erhalten Zugriff auf Tools für die Fehlerbehebung, Dokumentation und technische Support-Unterstützung.
+
https://mysupport.netapp.com/["NetApp Support"^]

* Zugriffsanforderungen und Kompatibilitätsinformationen zur Verwendung von ONTAP 9 und der ONTAP REST API.
+
https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^]

* Hier erhalten Sie technische Berichte, Whitepapers und weitere Dokumente.
+
http://www.netapp.com/us/library/index.aspx["NetApp Bibliothek mit technischen Berichten und Whitepapers"^]


