---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation, online reference, swagger 
summary: Die API-Referenz enthält Details zu den ONTAP-REST-API-Aufrufen, einschließlich der HTTP-Methoden, Eingabeparameter und Antworten. Diese vollständige Referenz ist hilfreich, wenn Automatisierungsapplikationen mithilfe der REST API entwickelt werden. 
---
= Referenz für die REST-API von ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die API-Referenz enthält Details zu den ONTAP-REST-API-Aufrufen, einschließlich der HTTP-Methoden, Eingabeparameter und Antworten. Diese vollständige Referenz ist hilfreich, wenn Automatisierungsapplikationen mithilfe der REST API entwickelt werden.


NOTE: Die REST-API-Referenzdokumentation ist an mehreren Standorten verfügbar, die auf der ONTAP Version basieren. Eine Kopie der entsprechenden Dokumentation ist auch über die Swagger-Benutzeroberfläche auf Ihrem lokalen ONTAP-System verfügbar.



== Die Referenzdokumentation zur ONTAP API ist online verfügbar

Sie können online auf die aktuelle Dokumentation zugreifen https://docs.netapp.com/us-en/ontap-restapi/ontap/getting_started_with_the_ontap_rest_api.html["ONTAP REST API Referenz"^]. Es steht auch eine Versionsauswahl zur Verfügung, um auf frühere Versionen der Dokumentation basierend auf der ONTAP-Version zuzugreifen.



== Greifen Sie über die Swagger-Benutzeroberfläche auf die Referenzdokumentation zur ONTAP-API zu

Sie können über die Swagger-Benutzeroberfläche Ihres lokalen ONTAP-Systems auf die ONTAP-REST-API-Dokumentation zugreifen.

.Bevor Sie beginnen
Sie müssen Folgendes haben:

* IP-Adresse oder Host-Name der ONTAP Cluster-Management-LIF
* Benutzername und Passwort für ein Konto mit Berechtigung für den Zugriff auf die ONTAP REST API


.Schritte
. Geben Sie die URL in Ihren Browser ein und drücken Sie *Enter*:
+
`https://<ip_address>/docs/api`

. Melden Sie sich über das ONTAP Konto an.
+
Die Dokumentationsseite für die ONTAP-API wird angezeigt, auf der die API-Aufrufe unten in den Hauptressourcenkategorien organisiert sind.

. Scrollen Sie als Beispiel für einen einzelnen API-Aufruf in die Kategorie *Cluster* und klicken Sie auf *GET /Cluster*.

