---
sidebar: sidebar 
permalink: workflows/wf_1_update_cluster_contact.html 
keywords: workflow 
summary: In diesem Workflow werden die Kontaktinformationen für das Cluster aktualisiert. Da die Anfrage asynchron verarbeitet wird, wird auch veranschaulicht, wie der Hintergrundjob erfolgreich abgeschlossen werden kann. 
---
= Workflow 1: Aktualisieren Sie den Cluster-Kontakt und überprüfen Sie den Job-Status
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Workflow werden die Kontaktinformationen für das Cluster aktualisiert. Da die Anfrage asynchron verarbeitet wird, wird auch veranschaulicht, wie der Hintergrundjob erfolgreich abgeschlossen werden kann.



=== 1. Aktualisieren Sie die Kontaktinformationen für das Cluster

Sie können einen API-Anruf ausstellen, um die Kontaktinformationen zu aktualisieren. Da die Anfrage asynchron ausgeführt wird, müssen Sie den Erfolg des zugehörigen Jobs bestätigen.

|===
| Kategorie | HTTP-Methode | Pfad 


| Cluster | PATCH | /Cluster 
|===
Asynchron

.Curl
[source, curl]
----
curl -X PATCH -H 'Content-Type: application/json' -u admin:password -k -d @step01 'https://10.222.81.101/api/cluster'
{
  "contact": "support@company-demo.com"
}
----
Ein Job-Objekt mit der zugeordneten ID wird zurückgegeben.

[source, json]
----
{ "job": {
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
  }
}
----


=== 2. Den Status des Jobs abrufen

Sie müssen den Status des Jobs abrufen, um festzustellen, ob die asynchrone Anforderung erfolgreich abgeschlossen wurde.

|===
| Kategorie | HTTP-Methode | Pfad 


| Cluster | GET | /Cluster/Jobs/{UUID} 
|===
Synchron

.Curl
[source, curl]
----
curl -X GET -H 'Content-Type: application/json' -u admin:password -k 'https:// 10.222.81.101/api/cluster/jobs/*uuid*'
----
Ein Job-Objekt mit dem Status und anderen Feldern wird zurückgegeben.

[source, json]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----