---
sidebar: sidebar 
permalink: workflows/wf_cls_update_contact.html 
keywords: workflow, update cluster, cluster contact 
summary: Sie können die Kontaktinformationen für ein Cluster aktualisieren. Da die Anforderung asynchron verarbeitet wird, müssen Sie auch feststellen, ob der zugehörige Hintergrundjob erfolgreich abgeschlossen wurde. 
---
= Cluster-Kontakt aktualisieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Kontaktinformationen für ein Cluster aktualisieren. Da die Anforderung asynchron verarbeitet wird, müssen Sie auch feststellen, ob der zugehörige Hintergrundjob erfolgreich abgeschlossen wurde.



== Schritt: Aktualisieren Sie die Kontaktinformationen des Clusters

Sie können einen API-Aufruf ausgeben, um die Kontaktinformationen des Clusters zu aktualisieren.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| PATCH | /API/Cluster 
|===
.Verarbeitungsart
Asynchron

.Beispiel für die Wellung
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON-Eingabebeispiel
[source, json]
----
{
  "contact": "support@company-demo.com"
}
----
.Beispiel für eine JSON-Ausgabe
Ein Jobobjekt wird zurückgegeben. Sie sollten die Jobkennung speichern, um sie im nächsten Schritt zu verwenden.

[listing]
----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----


== Schritt 2: Rufen Sie den Status des Jobs ab

Führen Sie den Workflow aus link:../workflows/wf_jobs_get_job.html["Job-Instanz abrufen"] Und bestätigen Sie die `state` Wert ist `success`.



== Schritt 3: Bestätigen Sie die Kontaktinformationen zum Cluster

Führen Sie den Workflow aus link:../workflows/wf_cls_get_cluster.html["Get Cluster-Konfiguration"]. Sie sollten die einstellen `fields` Abfrageparameter an `contact`.
