---
sidebar: sidebar 
permalink: workflows/wf_cls_get_cluster.html 
keywords: workflow, get cluster, cluster configuration 
summary: Sie können die Konfiguration für ein ONTAP Cluster einschließlich bestimmter Felder abrufen. Dies kann im Rahmen der Bewertung des Status des Clusters oder vor dem Aktualisieren der Konfiguration erfolgen. 
---
= Abrufen der Cluster-Konfiguration mit der ONTAP REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Konfiguration für ein ONTAP Cluster einschließlich bestimmter Felder abrufen. Dies kann im Rahmen der Bewertung des Status des Clusters oder vor dem Aktualisieren der Konfiguration erfolgen.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/Cluster 
|===
.Zusätzliche Eingabeparameter für Curl-Beispiele
Neben den bei allen REST API-Aufrufen üblichen Parametern werden in diesem Schritt auch die folgenden Parameter im Curl-Beispiel verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| Felder | Abfrage | Nein | Wählen Sie die Werte aus, die zurückgegeben werden sollen. Beispiele `contact` Und `version`. 
|===
.Curl Beispiel: Rufen Sie die Kontaktinformationen des Clusters ab
Dieses Beispiel zeigt, wie ein einzelnes Feld abgerufen wird. Um das gesamte Cluster-Objekt und die Konfiguration anzuzeigen, müssen Sie den entfernen `fields` Abfrageparameter.

[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster?fields=contact" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Beispiel für eine JSON-Ausgabe
[listing]
----
{
  "contact": "support@company-demo.com"
}
----