---
sidebar: sidebar 
permalink: workflows/wf_cert_install_certificate.html 
keywords: workflow, install certificate, x509, x.509 
summary: Sie können ein signiertes X.509-Zertifikat in Ihrem ONTAP-Cluster installieren. Dies kann im Rahmen der Konfiguration einer ONTAP-Funktion oder eines Protokolls erfolgen, für das eine starke Authentifizierung erforderlich ist. 
---
= Installieren Sie ein Zertifikat
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ein signiertes X.509-Zertifikat in Ihrem ONTAP-Cluster installieren. Dies kann im Rahmen der Konfiguration einer ONTAP-Funktion oder eines Protokolls erfolgen, für das eine starke Authentifizierung erforderlich ist.

.Bevor Sie beginnen
Sie müssen über das Zertifikat verfügen, das Sie installieren möchten. Stellen Sie außerdem sicher, dass alle Zwischenzertifikate bei Bedarf installiert sind.


CAUTION: Bevor Sie die folgenden JSON-Eingabebeispiele verwenden, müssen Sie das aktualisieren `public_certificate` Wert mit dem Zertifikat für Ihre Umgebung.



== Schritt 1: Installieren Sie das Zertifikat

Sie können einen API-Aufruf zur Installation des Zertifikats ausstellen.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/Security/Zertifikate 
|===
.Beispiel für Curl: Installieren Sie ein Stammzertifizierungsstellenzertifikat auf Cluster-Ebene
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/security/certificates" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON-Eingabebeispiel
[source, json]
----
{
    "type": "server_ca",
    "public_certificate":
    "-----BEGIN CERTIFICATE-----
MIID0TCCArkCFGYdznvTVvaY1VZPNfy4yCCyPph6MA0GCSqGSIb3DQEBCwUAMIGk
MQswCQYDVQQGEwJVUzELMAkGA1UECAwCTkMxDDAKBgNVBAcMA1JUUDEWMBQGA1UE
CgwNT05UQVAgRXhhbXBsZTETMBEGA1UECwwKT05UQVAgOS4xNDEcMBoGA1UEAwwT
Ki5vbnRhcC1leGFtcGxlLmNvbTEvMC0GCSqGSIb3DQEJARYgZGF2aWQucGV0ZXJz
b25Ab250YXAtZXhhbXBsZS5jb20wHhcNMjMxMDA1MTUyOTE4WhcNMjQxMDA0MTUy
OTE4WjCBpDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5DMQwwCgYDVQQHDANSVFAx
FjAUBgNVBAoMDU9OVEFQIEV4YW1wbGUxEzARBgNVBAsMCk9OVEFQIDkuMTQxHDAa
BgNVBAMMEyoub250YXAtZXhhbXBsZS5jb20xLzAtBgkqhkiG9w0BCQEWIGRhdmlk
LnBldGVyc29uQG9udGFwLWV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAxQgy8mhb1Jhkf0D/MBodpzgW0aSp2jGbWJ+Zv2G8BXkp1762
dPHRkv1hnx9JvwkK4Dba05GiCiD5t3gjH/jUQMSFb+VwDbVmubVFnXjkm/4Q7sea
tMtA/ZpQdZbQFZ5RKtdWz7dzzPYEl2x8Q1Jc8Kh7NxERNMtgupGWZZn7mfXKYr4O
N/+vgahIhDibS8YK5rf1w6bfmrik9E2D+PEab9DX/1DL5RX4tZ1H2OkyN2UxoBR6
Fq7l6n1Hi/5yR0Oi1xStN6sO7EPoGak+KSlK41q+EcIKRo0bP4mEQp8WMjJuiTkb
5MmeYoIpWEUgJK7S0M6Tp/3bTh2CST3AWxiNxQIDAQABMA0GCSqGSIb3DQEBCwUA
A4IBAQABfBqOuROmYxdfrj93OyIiRoDcoMzvo8cHGNUsuhnlBDnL2O3qhWEs97s0
mIy6zFMGnyNYa0t4i1cFsGDKP/JuljmYHjvv+2lHWnxHjTo7AOQCnXmQH5swoDbf
o1Vjqz8Oxz+PRJ+PA3dF5/8zqaAR6QreAN/iFR++6nUq1sbbM7w03tthBVMgo/h1
E9I2jVOZsqMFujm2CYfMs4XkZtrYmN6nZA8JcUpDjIWcAVbQYurMnna9r42oS3GB
WB/FE9n+P+FfJyHJ93KGcCXbH5RF2pi3wLlHilbvVuCjLRrhJ8U20I5mZoiXvABc
IpYuBcuKXLwAarhDEacXttVjC+Bq
-----END CERTIFICATE-----"
}
----


== Schritt 2: Bestätigen Sie, dass das Zertifikat installiert wurde

Führen Sie den Workflow aus link:../workflows/wf_cert_list_certificates.html["Listen Sie die installierten Zertifikate auf"] Und bestätigen Sie, dass das Zertifikat verfügbar ist.
