---
sidebar: sidebar 
permalink: workflows/wf_ems_create_notification.html 
keywords: support, ems, event management system, create ems, create ems notification 
summary: Sie können den folgenden Workflow verwenden, um ein neues EMS-Benachrichtigungsziel für den Empfang ausgewählter Ereignismeldungen zu erstellen. 
---
= Erstellen Sie eine EMS-Benachrichtigung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können den folgenden Workflow verwenden, um ein neues EMS-Benachrichtigungsziel für den Empfang ausgewählter Ereignismeldungen zu erstellen.



== Schritt 1: Konfigurieren Sie die systemweiten E-Mail-Einstellungen

Sie können den folgenden API-Aufruf durchführen, um die systemweiten E-Mail-Einstellungen zu konfigurieren.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| PATCH | /API/Support/ems 
|===
.Verarbeitungsart
Synchron

.Zusätzliche Eingabeparameter für die Curl-Beispiele
Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| Mail_von | Abfrage | Ja. | Legt den fest `from` In den Benachrichtigungs-E-Mail-Nachrichten. 


| Mail_Server | Abfrage | Ja. | Konfiguriert den Ziel-SMTP-Mailserver. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----


== Schritt 2: Definieren Sie einen Nachrichtenfilter

Sie können einen API-Aufruf ausgeben, um eine Filterregel zu definieren, die den Nachrichten entspricht.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/Support/ems/Filter 
|===
.Verarbeitungsart
Synchron

.Zusätzliche Eingabeparameter für die Curl-Beispiele
Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| Filtern | Text | Ja. | Enthält die Werte für die Filterkonfiguration. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/support/ems/filters" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON-Eingabebeispiel
[source, json]
----
{
  "name": "test-filter",
  "rules.type": ["include"],
  "rules.message_criteria.severities": ["emergency"]
}
----


== Schritt 3: Erstellen Sie ein Nachrichtenziel

Sie können einen API-Aufruf ausgeben, um ein Nachrichtenziel zu erstellen.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/Support/ems/Destinations 
|===
.Verarbeitungsart
Synchron

.Zusätzliche Eingabeparameter für die Curl-Beispiele
Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| Zielkonfiguration | Text | Ja. | Enthält die Werte für das Ereignisziel. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/support/ems/destinations" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON-Eingabebeispiel
[source, curl]
----
{
  "name": "test-destination",
  "type": "email",
  "destination": "administrator@mycompany.com",
  "filters.name": ["important-events"]
}
----