---
sidebar: sidebar 
permalink: workflows/wf_jobs_get_job.html 
keywords: workflow, job, job state 
summary: Sie können die Instanz eines bestimmten ONTAP-Jobs abrufen. In der Regel möchten Sie feststellen, ob der Job und der zugehörige Vorgang erfolgreich abgeschlossen wurden. 
---
= Job-Instanz abrufen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Instanz eines bestimmten ONTAP-Jobs abrufen. In der Regel möchten Sie feststellen, ob der Job und der zugehörige Vorgang erfolgreich abgeschlossen wurden.


NOTE: Sie benötigen die UUID des Jobobjekts, die normalerweise nach der Ausgabe einer asynchronen Anforderung bereitgestellt wird. Überprüfen Sie auch link:../rest/asynchronous_processing.html["Asynchrone Verarbeitung mit dem Job-Objekt"] Vor der Arbeit mit internen ONTAP Jobs.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/Cluster/Jobs/{uUID} 
|===
.Verarbeitungsart
Synchron

.Beispiel für die Wellung
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster/jobs/$JOB_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Beispiel für eine JSON-Ausgabe
Der Statuswert und andere Felder werden in das zurückgegebene Jobobjekt aufgenommen. Der Job in diesem Beispiel wurde im Rahmen der Aktualisierung eines ONTAP-Clusters ausgeführt.

[listing]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----