---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_get_permissions.html 
keywords: nas, file security, effective permissions 
summary: Sie können die aktuellen effektiven Berechtigungen für eine bestimmte Datei oder einen bestimmten Ordner abrufen. 
---
= Holen Sie sich die effektiven Berechtigungen für eine Datei
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die aktuellen effektiven Berechtigungen für eine bestimmte Datei oder einen bestimmten Ordner abrufen.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/protocols/file-Security/effective-permissions/{svm.uuid}/} path{ 
|===
.Verarbeitungsart
Synchron

.Zusätzliche Eingabeparameter für Curl-Beispiele
Neben den bei allen REST API-Aufrufen üblichen Parametern werden in diesem Schritt auch die folgenden Parameter im Curl-Beispiel verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| SVM_ID USD | Pfad | Ja. | Dies ist die UUID der SVM, die die Datei enthält. 


| PFAD FÜR DATEI | Pfad | Ja. | Dies ist der Pfad zur Datei oder zum Ordner. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/protocols/file-security/effective-permissions/$SVM_ID/$FILE_PATH" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Beispiel für eine JSON-Ausgabe
[listing]
----
{
  "svm": {
    "uuid": "cf5f271a-1beb-11ea-8fad-005056bb645e",
    "name": "vs1"
  },
  "user": "administrator",
  "type": "windows",
  "path": "/",
  "share": {
    "path": "/"
  },
  "file_permission": [
    "read",
    "write",
    "append",
    "read_ea",
    "write_ea",
    "execute",
    "delete_child",
    "read_attributes",
    "write_attributes",
    "delete",
    "read_control",
    "write_dac",
    "write_owner",
    "synchronize",
    "system_security"
  ],
  "share_permission": [
    "read",
    "read_ea",
    "execute",
    "read_attributes",
    "read_control",
    "synchronize"
  ]
}
----