---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_delete_ace.html 
keywords: nas, file security, access control entry, ace, delete ace 
summary: 'Sie können einen vorhandenen Access-Cotrol-Eintrag (ACE) aus einer bestimmten Datei oder einem bestimmten Ordner löschen. Die Änderung wird auf alle untergeordneten Objekte übertragen.' 
---
= Löschen eines Zugriffskontrolleintrags
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können einen vorhandenen ACE (Access Control Entry) aus einer bestimmten Datei oder einem bestimmten Ordner löschen. Die Änderung wird auf alle untergeordneten Objekte übertragen.



== Schritt 1: Die neuen Berechtigungen anwenden

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| Löschen | /API/protocols/file-Security/permissions/{svm.uuid}/} path{ 
|===
.Verarbeitungsart
Asynchron

.Zusätzliche Eingabeparameter für Curl-Beispiele
Neben den bei allen REST API-Aufrufen üblichen Parametern werden in diesem Schritt auch die folgenden Parameter im Curl-Beispiel verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| SVM_ID USD | Pfad | Ja. | Dies ist die UUID der SVM, die die Datei enthält. 


| PFAD FÜR DATEI | Pfad | Ja. | Dies ist der Pfad zur Datei oder zum Ordner. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request DELETE --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}'
----
.Beispiel für eine JSON-Ausgabe
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Schritt 2: Rufen Sie den Status des Jobs ab

Führen Sie den Workflow aus link:../workflows/wf_jobs_get_job.html["Job-Instanz abrufen"] Und bestätigen Sie die `state` Wert ist `success`.
