---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_update_sd.html 
keywords: nas, file security, security descriptor, sd, update security descriptor 
summary: Sie können eine bestimmte Sicherheitsbeschreibung auf eine bestimmte Datei oder einen bestimmten Ordner aktualisieren, einschließlich der primären Eigentümer-, Gruppen- oder Kontrollflags. 
---
= Aktualisieren Sie die Security Descriptor-Informationen mithilfe der ONTAP REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können eine bestimmte Sicherheitsbeschreibung auf eine bestimmte Datei oder einen bestimmten Ordner aktualisieren, einschließlich der primären Eigentümer-, Gruppen- oder Kontrollflags.



== Schritt 1: Aktualisieren Sie die Sicherheitsbeschreibung

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| PATCH | /API/protocols/file-Security/permissions/{svm.uuid}/} path{ 
|===
.Verarbeitungsart
Asynchron

.Zusätzliche Eingabeparameter für Curl-Beispiele
Neben den bei allen REST API-Aufrufen üblichen Parametern werden in diesem Schritt auch die folgenden Parameter im Curl-Beispiel verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| SVM_ID USD | Pfad | Ja. | Dies ist die UUID der SVM, die die Datei enthält. 


| PFAD FÜR DATEI | Pfad | Ja. | Dies ist der Pfad zur Datei oder zum Ordner. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}'
----
.Beispiel für eine JSON-Ausgabe
[listing]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Schritt 2: Rufen Sie den Status des Jobs ab

Führen Sie den Workflow aus link:../workflows/wf_jobs_get_job.html["Job-Instanz abrufen"] Und bestätigen Sie die `state` Wert ist `success`.
