---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_get_audit_info.html 
keywords: nas, file security, sacl, dacl, get auditing 
summary: Sie können alle Überwachungsinformationen für eine bestimmte Datei oder einen bestimmten Ordner abrufen. 
---
= Auditing-Informationen für eine Datei mithilfe der ONTAP REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Überwachungsinformationen für eine bestimmte Datei oder einen bestimmten Ordner abrufen.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/protocols/file-Security/permissions/{svm.uuid}/} path{ 
|===
.Verarbeitungsart
Synchron

.Zusätzliche Eingabeparameter für Curl-Beispiele
Neben den bei allen REST API-Aufrufen üblichen Parametern werden in diesem Schritt auch die folgenden Parameter im Curl-Beispiel verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| SVM_ID USD | Pfad | Ja. | Dies ist die UUID der SVM, die die Datei enthält. 


| PFAD FÜR DATEI | Pfad | Ja. | Dies ist der Pfad zur Datei oder zum Ordner. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Beispiel für eine JSON-Ausgabe
[listing]
----
{
  "svm": {
    "uuid": "9479099d-5b9f-11eb-9c4e-0050568e8682",
    "name": "vs1"
  },
  "path": "/parent",
  "owner": "BUILTIN\\Administrators",
  "group": "BUILTIN\\Administrators",
  "control_flags": "0x8014",
  "acls": [
    {
      "user": "BUILTIN\\Administrators",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    },
    {
      "user": "BUILTIN\\Users",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    }
  ],
  "inode": 64,
  "security_style": "mixed",
  "effective_style": "ntfs",
  "dos_attributes": "10",
  "text_dos_attr": "----D---",
  "user_id": "0",
  "group_id": "0",
  "mode_bits": 777,
  "text_mode_bits": "rwxrwxrwx"
}
----