---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_apply_permissions.html 
keywords: nas, file security, sacl, dacl, permissions, apply permissions 
summary: Sie können eine neue Sicherheitsbeschreibung auf eine bestimmte Datei oder einen bestimmten Ordner anwenden. 
---
= Anwenden neuer Berechtigungen auf eine Datei mithilfe der ONTAP-REST-API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können eine neue Sicherheitsbeschreibung auf eine bestimmte Datei oder einen bestimmten Ordner anwenden.



== Schritt 1: Die neuen Berechtigungen anwenden

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/protocols/file-Security/permissions/{svm.uuid}/} path{ 
|===
.Verarbeitungsart
Asynchron

.Zusätzliche Eingabeparameter für Curl-Beispiele
Neben den bei allen REST API-Aufrufen üblichen Parametern werden in diesem Schritt auch die folgenden Parameter im Curl-Beispiel verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| SVM_ID USD | Pfad | Ja. | Dies ist die UUID der SVM, die die Datei enthält. 


| PFAD FÜR DATEI | Pfad | Ja. | Dies ist der Pfad zur Datei oder zum Ordner. 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}'
----
.Beispiel für eine JSON-Ausgabe
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Schritt 2: Rufen Sie den Status des Jobs ab

Führen Sie den Workflow aus link:../workflows/wf_jobs_get_job.html["Job-Instanz abrufen"] Und bestätigen Sie die `state` Wert ist `success`.
