---
sidebar: sidebar 
permalink: workflows/wf_stor_list_disks.html 
keywords: workflow, storage, disks, list disks 
summary:  
---
= Festplatten auflisten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine Liste der Festplatten im Cluster abrufen. Sie könnten dies tun, um eine oder mehrere Ersatzteile zu finden, die als Teil der Erstellung eines Aggregats verwendet werden.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/Storage/Festplatten 
|===
.Verarbeitungsart
Synchron

.Zusätzliche Eingabeparameter für die Curl-Beispiele
Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| Bundesland | Abfrage | Nein | Kann verwendet werden, um die für neue Aggregate verfügbaren Ersatzfestplatten zu ermitteln. 
|===
.Beispiel für Curl: Geben Sie alle Festplatten zurück
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/disks" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Beispiel für Curl: Ersatzfestplatten zurückgeben
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/disks?state=spare" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Beispiel für eine JSON-Ausgabe
[%collapsible]
====
[listing]
----
{
  "records": [
    {
      "name": "NET-1.20",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.20"
        }
      }
    },
    {
      "name": "NET-1.12",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.12"
        }
      }
    },
    {
      "name": "NET-1.7",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.7"
        }
      }
    }
  ],
  "num_records": 3,
  "_links": {
    "self": {
      "href": "/api/storage/disks?state=spare"
    }
  }
}
----
====