---
sidebar: sidebar 
permalink: workflows/wf_stor_list_aggrs.html 
keywords: workflow, storage, aggregates, list aggregates 
summary:  
---
= Erstellen Sie eine Liste der Aggregate mithilfe der ONTAP REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können eine Liste der Aggregate im Cluster abrufen. Dies könnte Sie tun, um die Auslastung und die Performance zu beurteilen.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/Storage/Festplatten 
|===
.Verarbeitungsart
Synchron

.Zusätzliche Eingabeparameter für die Curl-Beispiele
Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| node.name | Abfrage | Nein | Kann verwendet werden, um den Node zu identifizieren, an den jedes Aggregat angeschlossen ist. 
|===
.Beispiel Curl: Gibt alle Aggregate mit den Standardkonfigurationswerten zurück
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/aggregates" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Curl Beispiel: Gibt alle Aggregate mit einem bestimmten Konfigurationswert zurück
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/aggregates?fields=node.name" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Beispiel für eine JSON-Ausgabe
[%collapsible]
====
[listing]
----
{
  "records": [
    {
      "uuid": "760d8137-fc59-47da-906a-cc28db0a1c1b",
      "name": "sti214_vsim_sr027o_aggr1",
      "node": {
        "name": "sti214-vsim-sr027o"
      },
      "_links": {
        "self": {
          "href": "/api/storage/aggregates/760d8137-fc59-47da-906a-cc28db0a1c1b"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/storage/aggregates?fields=node.name"
    }
  }
}
----
====