---
sidebar: sidebar 
permalink: python/overview_pcl.html 
keywords: overview, python client library, pcl 
summary: Die NetApp ONTAP Python Client Library ist ein Paket, mit dem Sie Skripts installieren und zum Schreiben von Skripten verwenden können, die auf die ONTAP REST API zugreifen. Mithilfe der Python-Client-Bibliothek können Sie schnell robusten Code zur Unterstützung der Automatisierung von ONTAP-Implementierungen entwickeln. 
---
= Überblick über die Python Client Library
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die NetApp ONTAP Python Client Library ist ein Paket, mit dem Sie Skripts installieren und zum Schreiben von Skripten verwenden können, die auf die ONTAP REST API zugreifen. Es unterstützt mehrere zugrunde liegende Services, darunter Verbindungs-Management, asynchrone Verarbeitung, Ausnahmebehandlung und Fehlermeldungen. Mithilfe der Python-Client-Bibliothek können Sie schnell robusten Code zur Unterstützung der Automatisierung von ONTAP-Implementierungen entwickeln.


NOTE: NetApp unterhält ein GitHub Repository, in dem Codebeispiele und andere hilfreiche Informationen enthalten sind. Sie können zum Ordner _examples_ navigieren, um mithilfe der Python-Client-Bibliothek auf Samples zuzugreifen.

.Verwandte Informationen
* https://github.com/NetApp/ontap-rest-python["ONTAP REST Python GitHub-Repository"^]
* https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["Beispiele für die ONTAP REST Python Client-Bibliothek"^]

