---
sidebar: sidebar 
permalink: python/prepare_pcl.html 
keywords: python client library, prepare, pcl 
summary: Sie sollten die lokale Laufzeitumgebung vorbereiten, bevor Sie die Python-Client-Bibliothek verwenden. 
---
= Vorbereiten der Verwendung der Python-Client-Bibliothek
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie sollten die lokale Laufzeitumgebung vorbereiten, bevor Sie die Python-Client-Bibliothek verwenden.

.Paketname und -Version
Der Name des Python Client Library-Pakets ist *netapp-ontap*. Die dem Paket zugeordnete Version ist eine Kombination aus den ONTAP-Major- und Minor-Versionsnummern, aus denen die Bibliothek erstellt wurde, sowie einer Minor-Version für den Client innerhalb der ONTAP-Version. Gültige Versionsnummern sind beispielsweise 9.6.1, 9.6 und 9.7.1.

.Installation
Sie müssen pip verwenden, um das netapp_ontap Paket von der Python Package Index (PyPi) Website zu installieren.

.Pakete und Dokumentation nach ONTAP Release
Jede ONTAP-Version, die mit 9.6 beginnt, verfügt über ein PyPI-Paket und die zugehörige Dokumentation. Siehe link:../python/packages.html["Pakete und Dokumentation"] Finden Sie weitere Informationen. Die Installationsanforderungen sind in jedem Paket enthalten und umfassen verschiedene Versionen der folgenden Komponenten:

* python
* Anträge
* Anforderungen-Werkzeuggürtel
* marshmallow

