---
sidebar: sidebar 
permalink: get-started/first_call.html 
keywords: first REST API call, test REST API 
summary: Sie können einen Curl-Befehl ausgeben, um die ONTAP REST-API zu verwenden und die Verfügbarkeit zu bestätigen. 
---
= Ihr erster API-Aufruf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können einen Curl-Befehl ausgeben, um die ONTAP REST-API zu verwenden und die Verfügbarkeit zu bestätigen.

.Bevor Sie beginnen
Neben der Verfügbarkeit des Curl-Dienstprogramms auf Ihrer Workstation benötigen Sie Folgendes:

* IP-Adresse oder FQDN der ONTAP Cluster-Management-LIF
* ONTAP-Anmeldedaten für ein Konto mit einer Berechtigung für den Zugriff auf die ONTAP-REST-API



NOTE: Wenn Ihre Anmeldeinformationen Sonderzeichen enthalten, müssen Sie sie entsprechend der verwendeten Shell formatieren. Sie können beispielsweise vor jedem Sonderzeichen einen umgekehrten Schrägstrich einfügen oder die gesamte Zeichenfolge der Anmeldeinformationen in doppelte Anführungszeichen umbrechen.

.Schritte
. Geben Sie an der Befehlszeilenschnittstelle Ihrer lokalen Arbeitsstation den folgenden Befehl ein:
+
[source, curl]
----
curl --request GET \
--user username:password \
"https://$FQDN_IP/api/cluster?fields=version"
----
+
*Beispiel*

+
`curl --request GET --user admin:david123 "https://10.222.81.101/api/cluster?fields=version"`



.Nachdem Sie fertig sind
Die Informationen zur ONTAP-Version werden in einem JSON-Format angezeigt.
