---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog 
summary: Es stehen verschiedene Optionen zur Verfügung, um die Implementierung und Administration Ihrer ONTAP Storage-Systeme zu automatisieren. 
---
= ONTAP-Automatisierungsoptionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es stehen verschiedene Optionen zur Verfügung, um die Implementierung und Administration Ihrer ONTAP Storage-Systeme zu automatisieren.



== ONTAP REST API

Ab ONTAP 9.6 bietet ONTAP eine umfassende REST-API, die die Grundlage für die Automatisierung der Implementierung und Administration Ihrer Storage-Systeme bietet. Seitdem hat sich die REST-API weiter erweitert und weiterentwickelt. Sie bietet jetzt die bevorzugte und strategische Option zur Automatisierung der Administration Ihrer ONTAP-Implementierungen. Bei der Verwendung der ONTAP REST-API müssen mehrere Aspekte berücksichtigt werden.

.Nativer Zugriff auf die REST-API
Sie können über jede Programmiersprache, die einen REST-Client unterstützt, direkt auf die ONTAP REST-API zugreifen. Beliebte Sprachen sind Python, PowerShell und Java.

.Migration von veraltetem ONTAPI Code zur Nutzung von REST
Die ONTAPI (ZAPI) ist die ursprüngliche Gruppe proprietärer Aufrufe der NetApp ONTAP Software, um die Automatisierung von Storage-Administrations- und Managementaufgaben zu unterstützen. Die ONTAPI Schnittstelle wird in zukünftigen Versionen von ONTAP deaktiviert. Wenn Sie bereits über Code verfügen, der die ONTAPI API verwendet, sollten Sie eine Migration von ONTAPI planen. NetApp bietet Unterstützung für die Konvertierung Ihres Codes zur Verwendung der neueren ONTAP-REST-API. Siehe link:../migrate/ontapi_disablement.html["Migration zur REST-API"] Finden Sie weitere Informationen.



== Toolkits für Clientsoftware

NetApp bietet Client-Toolkits, die die ONTAP-REST-API abstrahieren und die Erstellung von Automatisierungscode vereinfachen. Sie sollten eine geeignete für Ihre Entwicklungssprache und -Umgebung wählen.

.Python-Client-Bibliothek
Die Python-Client-Bibliothek ist ein Paket, das beim Schreiben von Skripten für den Zugriff auf die ONTAP REST-API verwendet werden kann. Es unterstützt mehrere zugrunde liegende Services, darunter Verbindungs-Management, asynchrone Anfragebearbeitung und Ausnahmebehandlung. Mithilfe der Python-Client-Bibliothek können Sie schnell robusten Code entwickeln, der Ihre ONTAP-Automatisierungsziele unterstützt. Siehe link:../python/overview_pcl.html["Python-Client-Bibliothek"] Finden Sie weitere Informationen.

.PowerShell Toolkit
Mit dem NetApp.ONTAP PowerShell Toolkit können Sie die Administration eines ONTAP Clusters von einem Windows Host aus automatisieren. Siehe https://review.docs.netapp.com/us-en/ontap-automation_devnet-update/pstk/overview_pstk.html["Überblick über das PowerShell Toolkit"^] Finden Sie weitere Informationen.



== Automatisierungs-Frameworks

Sie können Automatisierungscode mit einem von mehreren Frameworks erstellen und bereitstellen

.Ansible
Ansible ist ein Open-Source-Software-Tool, das Bereitstellung, Konfigurationsmanagement und Applikationseinsatz unterstützt. Seit der Veröffentlichung und der anschließenden Akquisition durch RedHat hat sich diese Beliebtheit stetig weiter entwickelt. NetApp bietet Ansible-zertifizierte Module, mit denen Kunden die Administration ihrer ONTAP Storage-Systeme automatisieren können. Siehe link:../additional/learn_more.html["Weitere Informationen ."] Und https://www.netapp.com/devops-solutions/ansible/["NetApp Ansible DevOps-Lösungen"^] Finden Sie weitere Informationen.

.BlueXP Automatisierungskatalog
Das NetApp https://console.bluexp.netapp.com/automationCatalog/["BlueXP Automatisierungskatalog"^] Ist über die BlueXP Web-Benutzeroberfläche verfügbar. Der Katalog bietet Zugriff auf Lösungspakete, mit deren Hilfe Sie die Implementierung und Integration von ONTAP in andere Produkte automatisieren können. Siehe https://docs.netapp.com/us-en/netapp-automation/["NetApp-Automatisierung"^] Für Dokumentation und weitere Informationen.
