---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog, netapp, console 
summary: Es stehen verschiedene Optionen zur Verfügung, um die Implementierung und Administration Ihrer ONTAP Storage-Systeme zu automatisieren. 
---
= ONTAP-Automatisierungsoptionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es stehen verschiedene Optionen zur Verfügung, um die Implementierung und Administration Ihrer ONTAP Storage-Systeme zu automatisieren.



== ONTAP REST API

Ab ONTAP 9.6 enthält ONTAP eine robuste REST-API, die die Grundlage für die Automatisierung der Bereitstellung und Verwaltung Ihrer Speichersysteme bietet.  Seitdem wurde die REST-API kontinuierlich erweitert und weiterentwickelt.  Es bietet jetzt die bevorzugte und strategische Option zur Automatisierung der Verwaltung Ihrer ONTAP Bereitstellungen.

.Nativer Zugriff auf die REST-API
Sie können über jede Programmiersprache, die einen REST-Client unterstützt, direkt auf die ONTAP REST-API zugreifen. Beliebte Sprachen sind Python, PowerShell und Java.

.Migration von veraltetem ONTAPI Code zur Nutzung von REST
Die ONTAPI-API (Zephyr-API oder ZAPI) ist der ursprüngliche Satz proprietärer Aufrufe, die in der NetApp ONTAP Software enthalten sind, um die Automatisierung Ihrer Datenspeicherverwaltungs- und -managementaufgaben zu unterstützen.  Die API ist Teil derlink:../sw-tools/learn-about-nmsdk.html["NetApp Manageability SDK"] .  Wenn Sie über vorhandenen Code verfügen, der die ONTAPI-API verwendet, sollten Sie Ihre Migration zur ONTAP REST-API planen, um die erweiterten Funktionen der REST-API zu nutzen.  NetApp bietet Unterstützung bei der Konvertierung Ihres Codes zur Verwendung der neueren ONTAP REST API. Sehen link:../migrate/migration-considerations.html["Migrieren Sie von ONTAPI zur REST-API"] für weitere Informationen.



== Toolkits für Clientsoftware

NetApp bietet Client-Toolkits, die die ONTAP-REST-API abstrahieren und die Erstellung von Automatisierungscode vereinfachen. Sie sollten eine geeignete für Ihre Entwicklungssprache und -Umgebung wählen.

.Python-Client-Bibliothek
Die Python-Client-Bibliothek ist ein Paket, das beim Schreiben von Skripten für den Zugriff auf die ONTAP REST-API verwendet werden kann. Es unterstützt mehrere zugrunde liegende Services, darunter Verbindungs-Management, asynchrone Anfragebearbeitung und Ausnahmebehandlung. Mithilfe der Python-Client-Bibliothek können Sie schnell robusten Code entwickeln, der Ihre ONTAP-Automatisierungsziele unterstützt. Weitere Informationen finden Sie unter link:../python/learn-about-pcl.html["Python-Client-Bibliothek"] .

.PowerShell Toolkit
Mit dem NetApp.ONTAP PowerShell Toolkit können Sie die Administration eines ONTAP Clusters von einem Windows Host aus automatisieren. Weitere Informationen finden Sie unter link:../pstk/learn-about-pstk.html["Erfahren Sie mehr über das NetApp PowerShell Toolkit"] .



== Automatisierungs-Frameworks

Sie können Automatisierungscode mithilfe eines von mehreren Frameworks erstellen und bereitstellen.

.Ansible
Ansible ist ein Open-Source-Software-Tool, das Bereitstellung, Konfigurationsmanagement und Applikationseinsatz unterstützt. Seit der Veröffentlichung und der anschließenden Akquisition durch RedHat hat sich diese Beliebtheit stetig weiter entwickelt. NetApp bietet Ansible-zertifizierte Module, mit denen Kunden die Administration ihrer ONTAP Storage-Systeme automatisieren können. Siehe link:../additional/learn_more.html["Weitere Informationen ."] Und https://www.netapp.com/devops-solutions/ansible/["NetApp Ansible DevOps-Lösungen"^] Finden Sie weitere Informationen.

.NetApp Console-Automatisierungskatalog
Die NetApp https://console.netapp.com/automationCatalog/["NetApp Console-Automatisierungskatalog"^] ist über die Web-Benutzeroberfläche der Konsole verfügbar.  Der Katalog bietet Zugriff auf Paketlösungen, die Ihnen bei der Automatisierung der Bereitstellung und Integration von ONTAP mit anderen Produkten helfen können.  Sehen https://docs.netapp.com/us-en/netapp-automation/["NetApp-Automatisierung"^] für Dokumentation und weitere Informationen.
