---
sidebar: sidebar 
permalink: rest/access_ontap_cli.html 
keywords: cli, ontap cli, cli passthrough 
summary: Um CLI- und ONTAPI-API-Benutzer bei ihrem Übergang zur ONTAP REST API zu unterstützen, stellt ONTAP einen REST-Endpunkt für den Zugriff auf die CLI bereit. Sie können diese Passthrough-Funktion verwenden, um jeden CLI-Befehl auszuführen. 
---
= Greifen Sie über die REST API auf die ONTAP-CLI zu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um CLI- und ONTAPI-API-Benutzer bei ihrem Übergang zur ONTAP REST API zu unterstützen, stellt ONTAP einen REST-Endpunkt für den Zugriff auf die CLI bereit. Sie können diese Passthrough-Funktion verwenden, um jeden CLI-Befehl auszuführen. Die Nutzung des REST-Endpunkts wird in AutoSupport-Daten zurückgegeben. NetApp kann Lücken in der REST-API identifizieren und in zukünftigen Versionen Verbesserungen vornehmen.

Um einen CLI-Befehl ausstellen zu können, müssen Sie einen REST-API-Aufruf tätigen, der entsprechend den folgenden Regeln ordnungsgemäß geformt ist:

* Ressourcenpfade
* Feldnamen
* HTTP-Methoden


Der grundlegende Ressourcenpfad für CLI-Zugriff ist `/private/cli`. Informationen zum Zugriff auf die CLI über DIE REST-API finden Sie auf der ONTAP-API-Seite mit der Online-Dokumentation.


NOTE: NetApp unterhält ein GitHub Repository, in dem Codebeispiele und andere hilfreiche Informationen enthalten sind. Sie können auf das Repository zugreifen, um Beispiele für die Verwendung der CLI-Passthrough-Einrichtung zu erhalten.

https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["ONTAP REST Python GitHub-Repository - CLI-Passthrough-Samples"^]
