---
sidebar: sidebar 
permalink: rest/input_variables.html 
keywords: variables, input, input variabls 
summary: Sie können steuern, wie ein API-Aufruf über Parameter und Variablen verarbeitet wird, die in der HTTP-Anforderung festgelegt sind. 
---
= Eingabevariablen, die eine API-Anforderung steuern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können steuern, wie ein API-Aufruf über Parameter und Variablen verarbeitet wird, die in der HTTP-Anforderung festgelegt sind.



== HTTP-Methoden

Die von der ONTAP REST API unterstützte HTTP-Methoden sind in der folgenden Tabelle aufgeführt.


NOTE: Nicht alle HTTP-Methoden sind an jedem REST-Endpunkt verfügbar. AUSSERDEM KÖNNEN PATCH und DELETE für eine Sammlung verwendet werden. Weitere Informationen finden Sie unter _Objektreferenzen und Zugang_.

[cols="20,80"]
|===
| HTTP-Methode | Beschreibung 


| GET | Ruft Objekteigenschaften auf einer Ressourceninstanz oder -Sammlung ab. 


| POST | Erstellt eine neue Ressourceninstanz basierend auf der angegebenen Eingabe. 


| PATCH | Aktualisiert eine vorhandene Ressourceninstanz basierend auf den eingegebenen Eingaben. 


| Löschen | Löscht eine vorhandene Ressourceninstanz. 


| KOPF | Gibt eine GET-Anfrage effektiv aus, gibt aber nur die HTTP-Header zurück. 


| OPTIONEN | Legen Sie fest, welche HTTP-Methoden an einem bestimmten Endpunkt unterstützt werden. 
|===


== Pfadvariablen

Der bei jedem REST-API-Aufruf verwendete Endpunktpfad kann verschiedene Kennungen enthalten. Jede ID entspricht einer bestimmten Ressourceninstanz. Beispiele sind Cluster-IDs und SVM-IDs.



== Anfragekopfzeilen

Sie müssen mehrere Header in die HTTP-Anfrage aufnehmen.

Inhaltstyp:: Wenn der Anforderungsentext JSON enthält, muss dieser Header auf festgelegt werden `application/json`.
Akzeptieren:: Diese Kopfzeile sollte auf gesetzt werden `application/hal+json`. Wenn sie stattdessen auf eingestellt ist `application/json` Keiner der HAL-Links wird zurückgegeben, außer ein Link, der zum Abrufen des nächsten Stapels von Datensätzen benötigt wird. Wenn der Header etwas anderes außer diesen beiden Werten ist, ist der Standardwert des `content-type` Die Kopfzeile in der Antwort ist `application/hal+json`.
Autorisierung:: Die grundlegende Authentifizierung muss mit dem Benutzernamen und dem Passwort als base64-Zeichenfolge codiert sein. Beispiel:
+
--
`Authorization: Basic YWRtaW46cGV0ZXJzb24=`.

--




== Text anfordern

Der Inhalt der Anfraentext variiert je nach Anruf. Der HTTP-Request-Text besteht aus einem der folgenden Elemente:

* JSON-Objekt mit Eingabevariablen
* Leeres JSON-Objekt




== Objekte filtern

Wenn Sie einen API-Aufruf ausgeben, der GET verwendet, können Sie die zurückgegebenen Objekte anhand eines beliebigen Attributs einschränken oder filtern. Sie können beispielsweise einen genauen Wert angeben, der übereinstimmt:

`<field>=<query value>`

Neben einer genauen Übereinstimmung stehen auch andere Operatoren zur Verfügung, um einen Satz von Objekten über einen Wertebereich zurückzugeben. Die ONTAP REST API unterstützt die in der nachfolgenden Tabelle aufgeführten Filteroperatoren.

|===
| Operator | Beschreibung 


| = | Gleich 


| < | Kleiner als 


| > | Größer als 


| \<= | Kleiner oder gleich 


| >= | Größer oder gleich 


| ! | Nicht gleich 


| * | Gierige Wildcard 
|===
Sie können auch eine Sammlung von Objekten zurückgeben, basierend darauf, ob ein bestimmtes Feld über die festgelegt wurde oder nicht `null` Stichwort oder Negation `!null` Als Teil der Abfrage.


NOTE: Nicht festgelegte Felder werden in der Regel von übereinstimmenden Abfragen ausgeschlossen.



== Es werden bestimmte Objektfelder angefordert

Standardmäßig gibt die Ausgabe eines API-Aufrufs mit GET nur die Attribute zurück, die das Objekt oder die Objekte eindeutig identifizieren, zusammen mit einer HAL-Selbstverknüpfung. Dieser minimale Feldsatz dient als Schlüssel für jedes Objekt und variiert je nach Objekttyp. Sie können zusätzliche Objekteigenschaften mithilfe der auswählen `fields` Abfrageparameter auf folgende Weise:

* Allgemeine oder Standardfelder
+
Angeben `fields=*`` Zum Abrufen der am häufigsten verwendeten Objektfelder. Diese Felder werden normalerweise im lokalen Serverspeicher verwaltet oder erfordern nur wenig Verarbeitung für den Zugriff. Dies sind die gleichen Eigenschaften, die für ein Objekt zurückgegeben werden, nachdem GET mit einem URL-Pfadschlüssel (UUID) verwendet wurde.

* Alle Felder
+
Angeben `fields=**` Zum Abrufen aller Objektfelder, einschließlich solcher, die für den Zugriff zusätzliche Serververarbeitung erforderlich sind.

* Benutzerdefinierte Feldauswahl
+
Nutzung `fields=<field_name>` Um das genaue Feld anzugeben, das Sie wünschen. Wenn Sie mehrere Felder anfordern, müssen die Werte durch Kommas ohne Leerzeichen getrennt werden.

+

TIP: Als Best Practice sollten Sie immer die gewünschten Felder identifizieren. Sie sollten nur die gemeinsamen Felder oder alle Felder abrufen, wenn Sie dies benötigen. Welche Felder werden als allgemein klassifiziert und mit zurückgegeben `fields=*`, Wird von NetApp basierend auf interner Performance-Analyse ermittelt. Die Klassifizierung eines Felds kann sich in zukünftigen Releases ändern.





== Sortieren von Objekten im Ausgabungsset

Die Datensätze in einer Ressourcensammlung werden in der vom Objekt definierten Standardreihenfolge zurückgegeben. Sie können die Bestellung über ändern `order_by` Abfrage-Parameter mit Feldname und Sortierrichtung wie folgt:

`order_by=<field name> asc|desc`

Sie können beispielsweise das Typfeld in absteigender Reihenfolge, gefolgt von id in aufsteigender Reihenfolge sortieren:

`order_by=type desc, id asc`

Beachten Sie Folgendes:

* Wenn Sie ein Sortierfeld angeben, aber keine Richtung angeben, werden die Werte in aufsteigender Reihenfolge sortiert.
* Wenn Sie mehrere Parameter eingeben, müssen Sie die Felder mit einem Komma trennen.




== Paginierung beim Abrufen von Objekten in einer Sammlung

Wenn ein API-Aufruf über GET auf eine Sammlung von Objekten desselben Typs zugreifen soll, versucht ONTAP, auf der Grundlage von zwei Einschränkungen so viele Objekte wie möglich zurückzugeben. Mit zusätzlichen Abfrageparametern auf der Anforderung können Sie jede dieser Einschränkungen steuern. Die erste Bedingung, die für eine bestimmte GET-Anforderung erreicht wurde, beendet die Anforderung und begrenzt damit die Anzahl der zurückgegebenen Datensätze.


NOTE: Wenn eine Anfrage endet, bevor sie alle Objekte anführt, enthält die Antwort den Link, der zum Abrufen des nächsten Stapels von Datensätzen benötigt wird.

Die Anzahl der Objekte wird begrenzt:: Standardmäßig gibt ONTAP maximal 10,000 Objekte für EINE GET-Anforderung aus. Sie können diese Begrenzung mit dem ändern `max_records` Abfrageparameter. Beispiel:
+
--
`max_records=20`

Die Anzahl der tatsächlich zurückgegebenen Objekte kann aufgrund der entsprechenden Zeitbeschränkung sowie der Gesamtanzahl der Objekte im System kleiner sein als die maximale Wirkung.

--
Begrenzung der Zeit, die zum Abrufen der Objekte verwendet wird:: Standardmäßig gibt ONTAP so viele Objekte wie möglich innerhalb der für die GET-Anforderung zulässigen Zeit zurück. Die Standard-Zeitüberschreitung beträgt 15 Sekunden. Sie können diese Begrenzung mit dem ändern `return_timeout` Abfrageparameter. Beispiel:
+
--
`return_timeout=5`

Die Anzahl der tatsächlich zurückgegebenen Objekte kann aufgrund der damit verbundenen Beschränkung auf die Anzahl der Objekte sowie die Gesamtanzahl der Objekte im System kleiner sein als die maximal zulässige Anzahl.

--
Verengung des Ergebnisset:: Bei Bedarf können Sie diese beiden Parameter mit zusätzlichen Abfrageparametern kombinieren, um den Ergebnissatz einzugrenzen. Im Folgenden werden z. B. bis zu 10 ems-Ereignisse zurückgegeben, die nach der angegebenen Zeit generiert wurden:
+
--
`time\=> 2018-04-04T15:41:29.140265Z&max_records=10`

Sie können mehrere Anfragen zur Seite durch die Objekte ausgeben. Jeder nachfolgende API-Aufruf sollte einen neuen Zeitwert verwenden, der auf dem letzten Ereignis des letzten Ergebnisset basiert.

--




== Größeneigenschaften

Die bei einigen API-Aufrufen verwendeten Eingabewerte sowie bestimmte Abfrageparameter sind numerisch. Anstatt eine ganze Zahl in Byte bereitzustellen, können Sie optional ein Suffix wie in der folgenden Tabelle aufgeführt verwenden.

[cols="20,80"]
|===
| Suffix | Beschreibung 


| KB | KB-Kilobyte (1024 Byte) oder Kibibyte 


| MB | MB Megabyte (KB x 1024 Byte) oder Mebibyte 


| GB | GB Gigabyte (MB x 1024 Byte) oder Gibibyte 


| TB | TB Terabyte (GB x 1024 Byte) oder Tebibyte 


| PB | PB (TB x 1024 Byte) oder Pebibyte 
|===
.Verwandte Informationen
* link:object_references_and_access.html["Objektreferenzen und -Zugriff"]

