---
sidebar: sidebar 
permalink: rest/rbac_wf_create_user.html 
keywords: rbac, workflow, create role, create user 
summary: Sie können den unten beschriebenen Workflow verwenden, um einen Benutzer mit einer zugehörigen REST-Rolle zu erstellen. Bevor Sie den Workflow überprüfen, sollten Sie sich mit den allgemeinen Vorbereitungsschritten vertraut machen. 
---
= Erstellen Sie einen Benutzer mit einer Rolle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können den unten beschriebenen Workflow verwenden, um einen Benutzer mit einer zugehörigen REST-Rolle zu erstellen. Bevor Sie den Workflow überprüfen, sollten Sie sich mit den allgemeinen Vorbereitungsschritten vertraut machen.



== Bereiten Sie die Erstellung eines ONTAP-Benutzers mit einer zugewiesenen Rolle vor

Bevor Sie eine Rolle erstellen und einem ONTAP-Benutzerkonto zuordnen, sollten Sie sich zunächst mit den wichtigsten Sicherheitsanforderungen und -Optionen vorbereiten.

Die ONTAP Version legt fest, welche REST-Endpunkte und RBAC-Funktionen verfügbar sind.

Sie müssen die zu sichernden Ressourcen oder Befehle und den Umfang (Cluster oder SVM) festlegen.

Nachdem Sie die Ressourcen und den Umfang ermittelt haben, müssen Sie die zuzugeteilte Zugriffsebene festlegen.

Der Benutzer kann über die REST-API oder über die CLI oder beide auf ONTAP zugreifen.

Es ist bequemer, eine vorhandene integrierte Rolle zu verwenden, aber Sie können bei Bedarf eine neue benutzerdefinierte Rolle erstellen.

Basierend auf den Sicherheitsanforderungen und dem ONTAP-Zugriff müssen Sie entscheiden, ob eine REST- oder eine herkömmliche Rolle erstellt werden soll.



== Erstellen Sie einen Benutzer mit einer benutzerdefinierten Rolle

Der unten beschriebene Workflow enthält die typischen Schritte, die zum Erstellen einer benutzerdefinierten REST-Rolle und zum Zuordnen einer neuen Benutzerkontos erforderlich sind. Sowohl der Benutzer als auch die Rolle haben einen Umfang der SVM und sind einer spezifischen Daten-SVM zugeordnet.


NOTE: Der Workflow soll den gesamten Prozess veranschaulichen. Einige der Schritte sind möglicherweise optional oder müssen je nach Ihrer Umgebung geändert werden.



=== 1. Liste der Daten-SVMs im Cluster

Führen Sie den folgenden REST-API-Aufruf durch, um die SVMs im Cluster aufzulisten. Die UUID und der Name jeder SVM werden in der Ausgabe angegeben.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/svm/svms 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms?order_by=name' -u admin:password -k --header 'Accept: */*'
----
Wählen Sie die gewünschte SVM aus der Liste aus, in der Sie den neuen Benutzer und die neue Rolle erstellen möchten.



=== 2. Listen Sie die Benutzer auf, die für die SVM definiert wurden

Führen Sie den folgenden REST-API-Aufruf durch, um die in der ausgewählten SVM definierten Benutzer aufzulisten. Sie können die SVM über den Eigner-Parameter angeben.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/Sicherheit/Konten 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/security/accounts/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'
----
Wählen Sie basierend auf den bereits in der SVM definierten Benutzern einen eindeutigen Namen für den neuen Benutzer aus.



=== 3. Listen Sie die REST-Rollen auf, die für die SVM definiert sind

Führen Sie den folgenden REST-API-Aufruf durch, um die in der ausgewählten SVM definierten Rollen aufzulisten. Sie können die SVM über den Eigner-Parameter angeben.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /API/Sicherheit/Funktionen 
|===
.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/security/roles/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'
----
Wählen Sie basierend auf den in der SVM bereits definierten Rollen einen eindeutigen Namen für die neue Rolle aus.



=== 4. Erstellen Sie eine benutzerdefinierte REST-Rolle

Führen Sie den folgenden REST-API-Aufruf zur Erstellung einer benutzerdefinierten REST-Rolle in der SVM aus. Die Rolle hat zunächst nur eine Berechtigung, die einen Standardzugriff von *none* schafft, so dass der Zugriff verweigert wird.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/Sicherheit/Funktionen 
|===
.JSON-Eingabebeispiel
[source, json]
----
{
  "name": "dprole1",
  "owner": {
    "name": "dmp",
    "uuid": "752d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api", "access": "none"},
  ]
}
----
.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/roles' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
Führen Sie optional Schritt 3 erneut aus, um die neue Rolle anzuzeigen. Sie können die Rollen auch in der ONTAP-CLI anzeigen.



=== 5. Aktualisieren Sie die Rolle, indem Sie weitere Berechtigungen hinzufügen

Führen Sie den folgenden REST-API-Aufruf durch, um die Rolle zu ändern, indem Sie nach Bedarf Berechtigungen hinzufügen.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/Sicherheit/Rollen/{owner.UUID}/{Name}/Privileges 
|===
.JSON-Eingabebeispiel
[source, json]
----
{
  "path": "/api/storage/volumes", "access": "readonly"}
}
----
.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/roles/752d96be-f17c-11ec-9d19-005056bbad91/dprole1/privileges' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
Führen Sie optional Schritt 3 erneut aus, um die neue Rolle anzuzeigen. Sie können die Rollen auch in der ONTAP-CLI anzeigen.



=== 6. Erstellen Sie einen Benutzer

Führen Sie den folgenden REST-API-Aufruf zu einem Benutzerkonto erstellen aus. Die Rolle `dprole1` Oben erstellte Daten sind dem neuen Benutzer zugeordnet.


TIP: Sie können den Benutzer auch ohne Rolle einbeziehen. In diesem Fall müssen Sie den Benutzer ändern, um eine Rolle zuzuweisen.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/Sicherheit/Konten 
|===
.JSON-Eingabebeispiel
[source, json]
----
{
  "owner": {"uuid":"daf84055-248f-11ed-a23d-005056ac4fe6"},
  "name": "david",
  "applications": [
      {"application":"ssh",
       "authentication_methods":["password"],
       "second_authentication_method":"none"}
  ],
  "role":"dprole1",
  "password":"netapp123"
}
----
.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/accounts' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
Sie können sich mit den Anmeldedaten für den neuen Benutzer bei der SVM-Managementoberfläche anmelden.
