---
sidebar: sidebar 
permalink: rest/rbac_sample_roles.html 
keywords: rbac, role definitions, samples 
summary: Die ONTAP RBAC-Funktion kann je nach Umgebung auf unterschiedliche Weise genutzt werden. Im Folgenden werden einige gängige Szenarien vorgestellt. In jedem Fall liegt der Fokus auf einem spezifischen Sicherheits- und Verwaltungsziel mit einem Beispiel für die entsprechende Rollendefinition. 
---
= BeispielRollendefinitionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die ONTAP RBAC-Funktion kann je nach Umgebung auf unterschiedliche Weise genutzt werden. Im Folgenden werden einige gängige Szenarien vorgestellt. In jedem Fall liegt der Fokus auf einem spezifischen Sicherheits- und Verwaltungsziel mit einem Beispiel für die entsprechende Rollendefinition.


NOTE: Alle Beispiele erstellen und ändern Rollen mit `/api/security/roles` Und die abgeleiteten REST-Endpunkte. Um Klarheit zu schaffen, bezieht sich jeder der Curl-Befehle auf eine separate JSON-Eingabedatei.



== Beschränkung des Zugriffs auf SVM-Volume-Vorgänge

Vielleicht möchten Sie die Administration von Storage Volume innerhalb einer SVM einschränken. Im folgenden Beispiel wird dies mit einer Rolle dargestellt, die zuerst erstellt und dann optional aktualisiert wird.



=== Erstellen Sie die ursprüngliche Rolle

In der herkömmlichen Rolle wird zunächst der Zugriff auf alle wichtigen Funktionen für die Volume-Administration außer dem Klonen gewährt. Die folgende Rolle ist dabei spezifisch definiert:

* Alle CRUD Volume-Vorgänge einschließlich get, create, modify und delete
* Volume-Klon kann nicht erstellt werden


.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON-Eingabebeispiel
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      { "path": "volume create", "access": "all" },
      { "path": "volume delete", "access": "all" }
    ]
}
----


=== Aktualisieren Sie die Rolle

Dieselbe Rolle kann geändert werden, damit der Benutzer auch einen Volume-Klon erstellen kann.

.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles/852d96be-f17c-11ec-9d19-005056bbad91/role1/privileges' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON-Eingabebeispiel
[source, json]
----
{
  "path": "volume clone",
  "access": "all"
}
----


== Datensicherung Administration

In bestimmten Situationen möchten Sie einen Benutzer mit eingeschränkten Datensicherungsfunktionen versorgen. Die unten dargestellte traditionelle Rolle ist definiert durch folgende Merkmale:

* Es sind möglich, Snapshots zu erstellen und zu löschen und auch SnapMirror Beziehungen zu aktualisieren
* Objekte höherer Ebene wie Volumes oder SVMs können nicht erstellt oder geändert werden


.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON-Eingabebeispiel
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "volume snapshot create", "access": "all"},
      {"path": "volume snapshot delete", "access": "all"},
      {"path": "volume show", "access": "readonly"},
      {"path": "vserver show", "access": "readonly"},
      {"path": "snapmirror show", "access": "readonly"},
      {"path": "snapmirror update", "access": "all"}
  ]
}
----


== ONTAP-Berichte werden erstellt

Sie können EINE REST-Rolle erstellen, um Benutzern die Möglichkeit zu geben, ONTAP-Berichte zu generieren. Die folgende Rolle ist dabei mit folgenden Eigenschaften definiert:

* Abrufen aller Kapazitäts- und Performance-Objektinformationen (u. a. Volume, qtree, LUN, Aggregate, Node, Und SnapMirror Beziehungen)
* Objekte höherer Ebene (wie Volumes oder SVMs) können nicht erstellt oder geändert werden.


.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON-Eingabebeispiel
[source, json]
----
{
  "name": "rest_role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api/storage/volumes", "access": "readonly"},
      {"path": "/api/storage/qtrees", "access": "readonly"},
      {"path": "/api/storage/luns", "access": "readonly"},
      {"path": "/api/storage/aggregates", "access": "readonly"},
      {"path": "/api/cluster/nodes", "access": "readonly"},
      {"path": "/api/snapmirror/relationships", "access": "readonly"},
      {"path": "/api/svm/svms", "access": "readonly"}
  ]
}
----