---
permalink: manage/dacl-sacl-rest-api.html 
sidebar: sidebar 
keywords: dacl, sacl, permissions, file, api, access, vserver, control, list, access control list, access control 
summary: Sie können die DACL- und SACL-Dateiberechtigungen mit der ONTAP REST API verwalten. 
---
= Managen Sie die DACL- und SACL-Dateiberechtigungen mit der ONTAP REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP weist Dateiobjekten mithilfe von System Access Control Lists (SACLs) und Ermessensary Access Control Lists (DACLs) Berechtigungen zu. Ab ONTAP 9.9 umfasst die ONTAP REST API Endpunkte, mit denen SACL- und DACL-Berechtigungen für Dateien zugewiesen und Dateisicherheitsberechtigungen automatisiert werden können. (Weitere Informationen zu Optionen für die Automatisierung von SACL- und DACL-Berechtigungen finden Sie vor ONTAP 9.9.1 https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["Hier"^]).

Ab ONTAP 9.9 können Sie einen einzelnen REST-API-Aufruf anstelle mehrerer CLI-Befehle oder ONTAPI-Aufrufe verwenden. Die folgenden Beispiele zeigen, wie Sie die ONTAP REST API zur Arbeit mit Dateiberechtigungen verwenden können. Stellen Sie in jedem Beispiel sicher, dass Sie Ihre Werte für Informationen in Klammern <> angeben.

Sie können auch auf ein Beispiel verweisen https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["Python-Skript"^] Das zeigt, wie eine Reihe von SACL- und DACL-Aktivitäten automatisiert werden kann.



== Anzeigen effektiver Berechtigungen

Verwenden der `GET /protocols/file-security/effective-permissions/` API-Aufruf können Sie die aktuellen Berechtigungen für eine bestimmte Datei oder ein bestimmtes Verzeichnis abrufen.

.Beispielanforderung:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/effective-permissions/cf5f271a-1beb-11ea-8fad-005056bb645e/administrator/windows/%2F?share.name=sh1&return_records=true'
----
.Beispielantwort
[source, json]
----
{
  "svm": {
    "uuid": "cf5f271a-1beb-11ea-8fad-005056bb645e",
    "name": "vs1"
  },
  "user": "administrator",
  "type": "windows",
  "path": "/",
  "share": {
    "path": "/"
  },
  "file_permission": [
    "read",
    "write",
    "append",
    "read_ea",
    "write_ea",
    "execute",
    "delete_child",
    "read_attributes",
    "write_attributes",
    "delete",
    "read_control",
    "write_dac",
    "write_owner",
    "synchronize",
    "system_security"
  ],
  "share_permission": [
    "read",
    "read_ea",
    "execute",
    "read_attributes",
    "read_control",
    "synchronize"
  ]
}
----


== Alle Audit-Informationen anzeigen

Verwenden der `GET /protocols/file-security/permissions/` API-Aufruf, Sie können alle Audit-Informationen für eine bestimmte Datei oder ein bestimmtes Verzeichnis abrufen.

.Beispielanforderung:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent'
----
.Beispielantwort
[source, json]
----
{
  "svm": {
    "uuid": "9479099d-5b9f-11eb-9c4e-0050568e8682",
    "name": "vs1"
  },
  "path": "/parent",
  "owner": "BUILTIN\\Administrators",
  "group": "BUILTIN\\Administrators",
  "control_flags": "0x8014",
  "acls": [
    {
      "user": "BUILTIN\\Administrators",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    },
    {
      "user": "BUILTIN\\Users",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    }
  ],
  "inode": 64,
  "security_style": "mixed",
  "effective_style": "ntfs",
  "dos_attributes": "10",
  "text_dos_attr": "----D---",
  "user_id": "0",
  "group_id": "0",
  "mode_bits": 777,
  "text_mode_bits": "rwxrwxrwx"
}

----


== Neue Berechtigungen anwenden

Verwenden der `POST /protocols/file-security/permissions/` API-Aufruf, Sie können einen neuen Sicherheitsdeskriptor auf eine Datei oder ein Verzeichnis anwenden.

.Beispielanforderung
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.Beispielantwort
[source, json]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Die Informationen zum Sicherheitsdeskriptor aktualisieren

Verwenden der `PATCH /protocols/file-security/permissions/` Über den API-Aufruf können Sie bestimmte Informationen zum Sicherheitsdeskriptor für eine Datei oder ein Verzeichnis aktualisieren, z. B. den primären Eigentümer, die Gruppe oder die Kontrollfahnen.

.Beispielanforderung
[source, curl]
----
curl -u admin:<PASSWORD> -X PATCH -d '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.Beispielantwort
[source, json]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Löschen eines vorhandenen SACL/DACL Access Control -Eintrags (ACE)

Verwenden der `DELETE /protocols/file-security/permissions/` API-Aufruf. Sie können einen vorhandenen ACE aus einer Datei für das Verzeichnis löschen. Dieses Beispiel propagiert die Änderung an untergeordnete Objekte.

.Beispielanforderung
[source, curl]
----
curl -u admin:<PASSWORD> -X DELETE -d '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent/acl/himanshu?return_timeout=0'
----
.Beispielantwort
[source, json]
----
{
  "job": {
    "uuid": "e5683b61-5bbf-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/e5683b61-5bbf-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== ONTAP REST API im Vergleich zu ONTAP-CLI-Befehlen

Mit der ONTAP REST API lassen sich Workflows mit weniger Befehlen als die ONTAP CLI für viele Aufgaben automatisieren. Beispielsweise können Sie mithilfe einer einzelnen POST-API-Methode einen Sicherheitsdeskriptor für eine Datei ändern, anstatt mehrere CLI-Befehle zu verwenden. Die folgende Tabelle zeigt die CLI-Befehle, die Sie benötigen würden, um allgemeine Dateiberechtigungsaufgaben des Dateisystems gegenüber den entsprechenden REST-API-Aufrufen durchzuführen:

|===
| ONTAP REST API | CLI VON ONTAP 


| `GET /protocols/file-security/effective-permissions/`  a| 
`vserver security file-directory show-effective-permissions`



| `POST /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs create`
. `vserver security file-directory ntfs dacl add`
. `vserver security file-directory ntfs sacl add`
. `vserver security file-directory policy create`
. `vserver security file-directory policy task add`
. `vserver security file-directory apply`




| `PATCH /protocols/file-security/permissions/`  a| 
`vserver security file-directory ntfs modify`



| `DELETE /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs dacl remove`
. `vserver security file-directory ntfs sacl remove`


|===


== Verwandte Informationen

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["Beispiel für Python-Skript mit ONTAP REST API-DACL/SACL-Berechtigungen"^]
* https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis/["Vereinfachtes Management von Dateisicherheitsberechtigungen mit ONTAP REST-APIs"^]
* https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["Verwenden der privaten CLI-Passthrough mit der ONTAP REST API (für Versionen von ONTAP vor Version 9.9.1)"^]

