---
permalink: manage/ems-rest-api.html 
sidebar: sidebar 
keywords: ems, configuration, workflow 
summary: Sie können die ONTAP EMS-Konfiguration über DIE REST API verwalten. 
---
= Verwalten Sie EMS-Ereignisbenachrichtigungen mit der ONTAP REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ONTAP REST API verwenden, um zu konfigurieren, wie wichtig Ereignis-Management-System (EMS) Ereignisbenachrichtigungen an Sie gesendet werden, sowie alle EMS-Nachrichten oder bestimmte Nachrichten mit bestimmten Attributen abzurufen. Sie können die REST-API verwenden, um EMS-bezogene Aufgaben zu automatisieren und so Zeit im Vergleich zu anderen Methoden der Arbeit mit EMS-Nachrichten zu sparen.

Die folgenden Beispiele zeigen Ihnen, wie Sie die ONTAP REST API zur Arbeit mit EMS-Nachrichten verwenden können. Stellen Sie in jedem Beispiel sicher, dass Sie Ihre Werte für Informationen in Klammern <> angeben. Sie können auch auf ein Beispiel verweisen https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["Python-Skript"^] Das zeigt, wie eine Reihe von EMS-bezogenen Aktivitäten automatisiert werden kann.



== Zeigen Sie bestimmte Ereignisprotokolle an

Verwenden der `GET /support/ems/events` API-Aufruf können Sie bestimmte Ereignismeldungen wie die letzte Meldung, Meldungen mit bestimmten Texten oder Meldungen mit einem bestimmten Schweregrad abrufen.

.Beispielanforderung: Aktuelle Nachricht abrufen
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?fields=message.name&max_records=1'
----
.Beispielantwort
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 6260,
      "message": {
        "name": "netinet6.rtr.high.mtu"
      },
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/6260"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?fields=message.name&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-22T10%3A28%3A29-04%3A00&start.node.name=malha-vsim1&start.index=6260&fields=message.name&max_records=1"
    }
  }
}
----
.Beispielanforderung: Abrufen einer Nachricht mit einem bestimmten Text und Schweregrad
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?log_message=*disk*&message.severity=alert'
----
.Beispielantwort
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----


== Die vorhandene EMS-Konfiguration anzeigen

Verwenden der `GET /support/ems/` API-Aufruf, Sie können Informationen über die vorhandene EMS-Benachrichtigungskonfiguration abrufen.

.Beispielanforderung
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/'
----
.Beispielantwort
[source, json]
----
{
  "proxy_url": "https://proxyserver.mycompany.com",
  "proxy_user": "proxy_user",
  "mail_server": "mail@mycompany.com",
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "pubsub_enabled": "1",
  "mail_from": "administrator@mycompany.com"
}
----


== Erstellen Sie eine neue EMS-Benachrichtigungskonfiguration

Sie können mehrere API-Aufrufe zusammen verwenden, um eine neue EMS-Konfiguration zu erstellen, um die Art und Weise, wann Sie Nachrichten empfangen, anzupassen.

.Schritte
. Konfigurieren Sie die systemweiten E-Mail-Einstellungen. Beispiel:
+
[source, curl]
----
curl -X PATCH -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com'
----
. Definieren Sie einen Filter, der bestimmte Regeln verwendet, um bestimmte Nachrichten zu erfüllen. Beispiel:
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-filter", "rules.type": ["include"], "rules.message_criteria.severities": ["emergency"]}' -k 'https://<IP_ADDRESS>/api/support/ems/filters/'
----
. Erstellen Sie ein Ziel für die Meldungen. Beispiel:
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-destination", "type": "email", "destination": "administrator@mycompany.com", "filters.name": ["important-events"]}' -k 'https://<IP_ADDRESS>/api/support/ems/destinations/'
----




== ONTAP REST API im Vergleich zu ONTAP-CLI-Befehlen

Mit der ONTAP REST API lassen sich Workflows mit weniger Befehlen als die ONTAP CLI für viele Aufgaben automatisieren. Beispielsweise können Sie einen Filter mithilfe einer einzelnen POST-API-Methode erstellen, anstatt mehrere CLI-Befehle zu verwenden. Die folgende Tabelle zeigt die CLI-Befehle, die Sie zur Erledigung allgemeiner EMS-Aufgaben im Vergleich mit den entsprechenden REST-API-Aufrufen benötigen würden:

|===
| ONTAP REST API | CLI VON ONTAP 


| `GET /support/ems` | `event config show` 


| `POST /support/ems/destinations`  a| 
. `event notification destination create`
. `event notification create`




| `GET /support/ems/events` | `event log show` 


| `POST /support/ems/filters`  a| 
. `event filter create -filter-name <filtername>`
. `event filter rule add -filter-name  <filtername>`


|===


== Verwandte Informationen

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["ONTAP REST API EMS, Beispiel Python-Skript"^]
* https://blog.netapp.com/ontap-rest-apis-automate-notification["ONTAP REST-APIs: Automatische Benachrichtigung über Ereignisse hoher Schweregrad"^]

